#!/usr/bin/env python3

"""
Script for tuning SignalGenerator and SignalProcessor parameters using recorded data.

Loads raw signal and feature coordinate data from an .npz file generated by
the main application's recorder. Allows interactive adjustment of processing
parameters and visualizes the raw and filtered signals.
"""

import sys
import os
import time
import numpy as np
import traceback
import argparse
from scipy import signal as scipy_signal # For window functions
import json

# --- PyQt6 Imports ---
try:
    from PyQt6.QtWidgets import (
        QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
        QGroupBox, QFormLayout, QLabel, QDoubleSpinBox, QComboBox,
        QPushButton, QSizePolicy, QSpacerItem, QFileDialog, QCheckBox, QMessageBox, QGridLayout, QLineEdit, QSpinBox,
        QSlider # Import QSlider
    )
    from PyQt6.QtCore import QTimer, Qt, pyqtSlot
    from PyQt6.QtGui import QFont
    import pyqtgraph as pg
    print("Using PyQt6 and pyqtgraph")
except ImportError as e:
    print(f"Fatal Error: Missing required libraries (PyQt6, pyqtgraph). {e}")
    print("Please install them (e.g., pip install PyQt6 pyqtgraph)")
    sys.exit(1)

# --- Add src directory to Python path ---
script_dir = os.path.dirname(os.path.abspath(__file__))
src_dir = os.path.join(script_dir, '..', 'src')
if src_dir not in sys.path:
    sys.path.insert(0, src_dir)
    print(f"Added '{src_dir}' to Python path.")

# --- Import Processing Components ---
try:
    from signal_generator import SignalGenerator
    from signal_processor import SignalProcessor
    # Note: FeatureTracker is not directly used by the tuner, only its config keys
except ImportError as e:
    print(f"Fatal Error: Failed to import SignalGenerator or SignalProcessor from 'src': {e}")
    traceback.print_exc()
    sys.exit(1)

# --- Constants ---
DEFAULT_RECORDING_DIR = os.path.abspath(os.path.join(script_dir, '..', 'recordings'))
DEFAULT_RUN_NAME = "run_1" # Placeholder, adjust as needed or use argparse
DEFAULT_NPZ_FILE = "raw_pipeline_data.npz"

# --- Feature Plot Window ---
class FeaturePlotWindow(QWidget):
    """A separate window to display feature points (X vs Y) for a specific time."""
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Feature Point Positions")
        # Initial size will be set relative to the main window later

        self.timestamps = None
        self.feature_coords = None # List of arrays
        self.center_of_mass = np.array([0.0, 0.0]) # Store the initial center
        self.initial_plot_set = False # Flag to set range only once

        layout = QVBoxLayout(self)
        self.plot_widget = pg.PlotWidget()
        layout.addWidget(self.plot_widget)

        self.plot_widget.setAspectLocked(True) # Ensure X and Y scales are equal
        self.plot_widget.setLabel('left', 'Y Coordinate')
        self.plot_widget.setLabel('bottom', 'X Coordinate')
        self.plot_widget.showGrid(x=True, y=True, alpha=0.3)
        # Invert Y axis to match typical image coordinates (optional)
        self.plot_widget.invertY(True)

        self.scatter_item = pg.ScatterPlotItem(size=5, pen=None, brush='r')
        self.plot_widget.addItem(self.scatter_item)

        # Set larger font for axes if needed (can inherit from main window later)
        # default_font = QApplication.font()
        # self.plot_widget.getAxis('left').setTickFont(default_font)
        # self.plot_widget.getAxis('bottom').setTickFont(default_font)

    def set_data(self, timestamps, feature_coords):
        self.timestamps = timestamps
        self.feature_coords = feature_coords
        print(f"[FeatureWindow] Received data: {len(timestamps)} timestamps, {len(feature_coords)} coord sets.")

        # --- Calculate initial center of mass ---
        self.center_of_mass = np.array([0.0, 0.0]) # Reset
        # --- MODIFIED: Explicitly check for None before checking length ---
        if self.feature_coords is not None and len(self.feature_coords) > 0: # Check if feature_coords exists and is not empty
            first_frame_points = self.feature_coords[0]
            if first_frame_points is not None and first_frame_points.ndim >= 2 and first_frame_points.shape[-1] == 2 and len(first_frame_points) > 0:
                # Reshape to (N, 2) and calculate mean
                points_2d = first_frame_points.reshape(-1, 2)
                self.center_of_mass = np.mean(points_2d, axis=0)
                # --- Calculate initial relative points for range setting ---
                initial_relative_points = points_2d - self.center_of_mass
                print(f"[FeatureWindow] Calculated initial center of mass: {self.center_of_mass}") # Keep this print
                # --- ADDED DEBUG PRINT ---
                print(f"[FeatureWindow Debug] Center X: {self.center_of_mass[0]:.2f}, Center Y: {self.center_of_mass[1]:.2f}")

                # --- Calculate overall range based on ALL relative points ---
                all_relative_points_list = []
                for frame_points in self.feature_coords:
                    if frame_points is not None and frame_points.ndim >= 2 and frame_points.shape[-1] == 2 and len(frame_points) > 0:
                        relative = frame_points.reshape(-1, 2) - self.center_of_mass
                        all_relative_points_list.append(relative)

                if all_relative_points_list:
                    all_relative_points = np.vstack(all_relative_points_list)
                    min_x, max_x = np.min(all_relative_points[:, 0]), np.max(all_relative_points[:, 0])
                    min_y, max_y = np.min(all_relative_points[:, 1]), np.max(all_relative_points[:, 1])
                    padding_factor = 1.1 # Add 10% padding
                    # Calculate range width/height and center it
                    range_x = (max_x - min_x) * padding_factor
                    range_y = (max_y - min_y) * padding_factor
                    center_x = (max_x + min_x) / 2
                    center_y = (max_y + min_y) / 2
                    self.initial_plot_range = ((center_x - range_x / 2, center_x + range_x / 2),
                                               (center_y - range_y / 2, center_y + range_y / 2))
                    print(f"[FeatureWindow] Calculated overall plot range: X={self.initial_plot_range[0]}, Y={self.initial_plot_range[1]}")
                else:
                    self.initial_plot_range = None # Fallback if no valid points found after first frame
            else:
                print("[FeatureWindow] Warning: No valid points in the first frame to calculate center of mass.")
                points_2d = None # Ensure points_2d is defined
                self.initial_plot_range = None
        else:
            print("[FeatureWindow] Warning: No feature coordinate data provided.")
            points_2d = None # Ensure points_2d is defined

    def update_plot(self, frame_index):
        if self.feature_coords is None or not (0 <= frame_index < len(self.feature_coords)):
            self.scatter_item.setData([]) # Clear plot if index is invalid
            self.plot_widget.setTitle("Feature Points (No Data)")
            return

        points = self.feature_coords[frame_index]
        # --- MODIFIED: Check for (N, 2) or (N, 1, 2) shape ---
        if points is not None and points.ndim >= 2 and points.shape[-1] == 2:
            # Reshape to (N, 2) if necessary
            points_to_plot = points.reshape(-1, 2)
            # Subtract center of mass
            relative_points = points_to_plot - self.center_of_mass
            # --- Plot relative points ---
            self.scatter_item.setData(pos=relative_points)

            # --- Set range and disable auto-range ONCE after first plot ---
            if not self.initial_plot_set:
                if self.initial_plot_range: # Use calculated overall range if available
                    self.plot_widget.setXRange(*self.initial_plot_range[0], padding=0)
                    self.plot_widget.setYRange(*self.initial_plot_range[1], padding=0)
                    self.plot_widget.getViewBox().disableAutoRange()
                    self.initial_plot_set = True
                print(f"[FeatureWindow] Set fixed plot range and disabled auto-range.")

            current_time = self.timestamps[frame_index] if self.timestamps is not None else 0.0
            self.plot_widget.setTitle(f"Relative Feature Points @ {current_time:.2f}s (Frame {frame_index})")
        else:
            self.scatter_item.setData([]) # Clear plot if data for frame is invalid
            # --- DEBUG PRINT ---
            print(f"[FeatureWindow Debug] Invalid data at index {frame_index}. Type: {type(points)}, Shape: {points.shape if hasattr(points, 'shape') else 'N/A'}, Is None: {points is None}")
            self.plot_widget.setTitle(f"Feature Points (Invalid Data @ Frame {frame_index})")

# --- NEW: PCA Vector Window ---
class PCAVectorWindow(QWidget):
    """A separate window to display feature displacements and the principal component."""
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("PCA Displacement Vector")
        self.min_features_for_pca = 3 # Minimum points needed

        layout = QVBoxLayout(self)
        self.plot_widget = pg.PlotWidget()
        layout.addWidget(self.plot_widget)

        self.plot_widget.setAspectLocked(True)
        self.plot_widget.setLabel('left', 'dY (pixels)')
        self.plot_widget.setLabel('bottom', 'dX (pixels)')
        self.plot_widget.showGrid(x=True, y=True, alpha=0.3)
        # Set initial range to avoid extreme zoom on first frame
        self.plot_widget.setRange(xRange=(-10, 10), yRange=(-10, 10), disableAutoRange=True)
        self.plot_widget.setTitle("Centered Displacements & PCA Vector")

        # Scatter plot for centered displacements
        self.scatter_item = pg.ScatterPlotItem(size=5, pen=None, brush=(255, 0, 0, 150)) # Red points (RGBA)
        self.plot_widget.addItem(self.scatter_item)

        # Arrow item for PCA vector
        self.pca_arrow = pg.ArrowItem(pen=pg.mkPen('y', width=2), brush='y')
        self.plot_widget.addItem(self.pca_arrow)

        # --- NEW: Arrow item for Mean Displacement Vector ---
        self.mean_disp_arrow = pg.ArrowItem(pen=pg.mkPen('c', width=1, style=Qt.PenStyle.DashLine), brush='c') # Cyan dashed
        self.plot_widget.addItem(self.mean_disp_arrow)

        # --- NEW: Ellipse item for Variance ---
        self.variance_ellipse = pg.Qt.QtWidgets.QGraphicsEllipseItem() # Access via pg.Qt.QtWidgets
        self.variance_ellipse.setPen(pg.mkPen(color=(255, 255, 255, 150), width=1)) # Semi-transparent white
        self.plot_widget.addItem(self.variance_ellipse)

        # Text item for status
        self.status_text = pg.TextItem(anchor=(0, 1), color=(200, 200, 200)) # White text, top-left
        self.plot_widget.addItem(self.status_text)

    def update_plot(self, frame_index, old_points, new_points):
        """Calculates PCA and updates the plot for the given frame data."""
        self.scatter_item.clear()
        self.pca_arrow.setStyle(headLen=0) # Hide arrow initially
        self.mean_disp_arrow.setStyle(headLen=0) # Hide mean arrow initially
        self.variance_ellipse.setRect(0, 0, 0, 0) # Hide ellipse
        self.status_text.setText("")

        if old_points is None or new_points is None or \
           len(old_points) < self.min_features_for_pca or len(old_points) != len(new_points):
            self.status_text.setText(f"Frame {frame_index}: Insufficient/Invalid Points")
            return

        try:
            # --- Ensure (N, 2) shape ---
            old_p = old_points.reshape(-1, 2)
            new_p = new_points.reshape(-1, 2)

            # --- Robust Filtering for object dtype or non-finite numbers ---
            valid_indices = []
            for idx in range(old_p.shape[0]):
                # Check if all four coordinate values are finite numbers
                is_valid_row = all(
                    isinstance(coord, (int, float)) and np.isfinite(coord)
                    for coord in [old_p[idx, 0], old_p[idx, 1], new_p[idx, 0], new_p[idx, 1]]
                )
                if is_valid_row:
                    valid_indices.append(idx)

            if len(valid_indices) < self.min_features_for_pca:
                self.status_text.setText(f"Frame {frame_index}: Too few valid numeric points ({len(valid_indices)}) for PCA")
                return

            # Create new numeric arrays using only valid indices
            old_p_numeric = old_p[valid_indices].astype(float) # Ensure float dtype
            new_p_numeric = new_p[valid_indices].astype(float) # Ensure float dtype

            # Calculate displacements only on valid, finite points
            displacements = new_p_numeric - old_p_numeric
            # --- End input filtering ---

            # --- NEW: Filter out non-finite displacements ---
            finite_mask = np.all(np.isfinite(displacements), axis=1)
            displacements = displacements[finite_mask]
            if displacements.shape[0] < self.min_features_for_pca: # Check again after filtering
                self.status_text.setText(f"Frame {frame_index}: Too few finite points ({displacements.shape[0]}) for PCA")
                return
            # --- End Filter ---

            # Center the displacements
            mean_disp = np.mean(displacements, axis=0)
            centered_disp = displacements - mean_disp

            # --- Update Mean Displacement Arrow ---
            mean_disp_len = np.linalg.norm(mean_disp)
            if mean_disp_len > 1e-6: # Only show if mean displacement is significant
                self.mean_disp_arrow.setPos(0, 0)
                self.mean_disp_arrow.setStyle(
                    headLen=10, # Smaller head
                    tailLen=mean_disp_len,
                    tailWidth=1,
                    angle=np.degrees(np.arctan2(mean_disp[1], mean_disp[0]))
                )
            # --- End Mean Displacement Arrow ---


            # --- Add Check: Ensure at least 2 data points for covariance ---
            if centered_disp.shape[0] < 2:
                self.status_text.setText(f"Frame {frame_index}: Too few points ({centered_disp.shape[0]}) for PCA")
                self.scatter_item.setData(pos=centered_disp) # Still plot the single point if it exists
                return
            # --- End Check ---
            # Plot centered displacements
            self.scatter_item.setData(pos=centered_disp)

            # --- Add Check: Ensure input to np.cov is 2D with at least 2 rows ---
            if not isinstance(centered_disp, np.ndarray) or centered_disp.ndim != 2 or centered_disp.shape[0] < 2 or centered_disp.shape[1] != 2:
                self.status_text.setText(f"Frame {frame_index}: Invalid shape for PCA ({centered_disp.shape if hasattr(centered_disp, 'shape') else type(centered_disp)})")
                print(f"[PCA Debug] Invalid shape for PCA input: {centered_disp.shape if hasattr(centered_disp, 'shape') else type(centered_disp)}")
                return
            # --- End Check ---

            # --- NEW Check: Ensure dtype is numeric before allclose ---
            if not np.issubdtype(centered_disp.dtype, np.number):
                self.status_text.setText(f"Frame {frame_index}: Non-numeric data for PCA")
                print(f"[PCA Debug] Non-numeric dtype detected before np.allclose: {centered_disp.dtype}")
                return
            # --- End NEW Check ---

            # --- NEW Check: Handle zero variance case before np.cov ---
            if np.allclose(centered_disp, centered_disp[0], atol=1e-6): # Check if all rows are close to the first row
                self.status_text.setText(f"Frame {frame_index}: Zero variance in displacements")
                print(f"[PCA Debug] Zero variance detected before np.cov")
                # Optionally plot the points if needed, they will overlap
                self.scatter_item.setData(pos=centered_disp)
                return
            # --- End NEW Check ---
            # Calculate PCA
            cov_matrix = np.cov(centered_disp, rowvar=False)
            if np.allclose(cov_matrix, 0, atol=1e-6):
                self.status_text.setText(f"Frame {frame_index}: Zero Covariance")
                return

            eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)
            # Sort eigenvalues and eigenvectors in descending order
            sort_indices = np.argsort(eigenvalues)[::-1]
            eigenvalues_sorted = eigenvalues[sort_indices]
            eigenvectors_sorted = eigenvectors[:, sort_indices]

            principal_component = eigenvectors_sorted[:, 0] # First principal component (largest eigenvalue)
            secondary_component = eigenvectors_sorted[:, 1] # Second principal component

            # Standard deviations along principal axes
            std_dev1 = np.sqrt(max(0, eigenvalues_sorted[0])) # Ensure non-negative
            std_dev2 = np.sqrt(max(0, eigenvalues_sorted[1])) # Ensure non-negative

            # --- Update Variance Ellipse ---
            ellipse_scale = 2.0 # Scale factor (e.g., 2 for ~95% confidence)
            ellipse_width = std_dev1 * ellipse_scale * 2 # Full width (diameter)
            ellipse_height = std_dev2 * ellipse_scale * 2 # Full height (diameter)
            ellipse_angle = np.degrees(np.arctan2(principal_component[1], principal_component[0]))

            # QGraphicsEllipseItem is defined by its top-left corner and width/height
            # We need to center it at (0,0)
            ellipse_rect = pg.QtCore.QRectF(-ellipse_width / 2, -ellipse_height / 2, ellipse_width, ellipse_height)
            self.variance_ellipse.setRect(ellipse_rect)
            self.variance_ellipse.setRotation(ellipse_angle) # Rotate around its center
            # --- End Variance Ellipse ---

            # Scale vector for visibility (e.g., based on std dev of projections)
            projections = np.dot(centered_disp, principal_component) # Projections onto first PC
            vector_scale = np.std(projections) * 2.0 # Scale by 2x std dev
            scaled_vector = principal_component * vector_scale

            # --- Corrected: Use setStyle for arrow parameters ---
            self.pca_arrow.setPos(0, 0) # Start at origin
            self.pca_arrow.setStyle(
                headLen=15,
                tipAngle=30,
                baseAngle=20,
                tailLen=np.linalg.norm(scaled_vector),
                tailWidth=2,
                angle=np.degrees(np.arctan2(scaled_vector[1], scaled_vector[0])) # Angle in degrees
            )
            self.status_text.setText(f"Frame {frame_index}: PCA OK ({len(displacements)} pts)")

        except np.linalg.LinAlgError:
            self.status_text.setText(f"Frame {frame_index}: LinAlgError in PCA")
        except Exception as e:
            self.status_text.setText(f"Frame {frame_index}: Error: {e}")
            print(f"PCA Window Error: {e}")
            traceback.print_exc()

class TuningWindow(QMainWindow):
    """Main window for the signal processing tuning application."""

    def __init__(self, npz_file_path, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Signal Processing Tuner")
        # --- Make main window wider ---
        self.setGeometry(100, 100, 1200, 800) # Increased width from 1000 to 1200

        # Data storage
        self.timestamps = None
        self.raw_signal_loaded = None
        self.feature_coords = None
        self.sampling_rate = 30.0 # Default, will be updated from data

        # Processed data storage
        self.raw_signal_processed = None
        self.filtered_signal_processed = None

        # Processing components
        self.signal_generator = None
        self.signal_processor = None

        # Playback state
        self.playback_timer = QTimer(self)
        self.playback_timer.timeout.connect(self._update_playback_cursor)
        self.current_frame_index = 0
        self.playback_start_time = 0
        self.is_playing = False
        self.playback_speed = 1.0 # Added playback speed multiplier

        # Histogram range storage
        self.hist_x_range = None
        self.hist_y_range = None

        # --- Set Larger Font ---
        default_font = QApplication.font()
        default_point_size = default_font.pointSize()
        if default_point_size < 8: default_point_size = 10 # Ensure a minimum base size
        new_point_size = int(default_point_size * 1.08) # Increase by 8%
        self.larger_font = QFont(default_font)
        self.larger_font.setPointSize(new_point_size)
        self.setFont(self.larger_font)
        print(f"[UI] Setting base font size to {new_point_size}pt (was {default_point_size}pt)")

        # --- Create Feature Plot Window ---
        self.feature_plot_window = FeaturePlotWindow()
        self.feature_plot_window.setFont(self.larger_font) # Apply larger font
        # --- Position feature window next to main window ---
        main_geo = self.geometry()
        feature_win_x = main_geo.x() + main_geo.width() + 10 # Position to the right with a small gap
        feature_win_y = main_geo.y()
        feature_win_height = main_geo.height() # Match main window height
        feature_win_width = feature_win_height # Make width equal to height (square)
        self.feature_plot_window.setGeometry(feature_win_x, feature_win_y, feature_win_width, feature_win_height)

        # --- Create PCA Vector Window ---
        self.pca_vector_window = PCAVectorWindow()
        self.pca_vector_window.setFont(self.larger_font)
        # Position below feature window
        pca_win_x = feature_win_x
        pca_win_y = feature_win_y + feature_win_height + 30 # Below feature window with gap
        self.pca_vector_window.setGeometry(pca_win_x, pca_win_y, feature_win_width, feature_win_height) # Same size
        # --- End PCA Vector Window ---

        self._init_ui()
        self.load_data(npz_file_path)
        self._reprocess_data() # Initial processing and plot population
        # --- Show feature plot window by default ---
        self.feature_plot_window.show()

    def _init_ui(self):
        """Creates and arranges UI elements."""
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        main_layout = QHBoxLayout(central_widget) # Horizontal: Plots | Controls

        # --- Plots Area ---
        plot_widget_container = QWidget()
        plot_layout = QVBoxLayout(plot_widget_container)

        # --- Plot Appearance Changes ---
        pg.setConfigOption('background', 'k') # Black background
        pg.setConfigOption('foreground', 'w') # White foreground (axes, labels)

        self.raw_plot_widget = pg.PlotWidget(title="Raw Motion Signal")
        self.raw_plot_widget.setLabel('left', 'Amplitude')
        self.raw_plot_widget.showGrid(x=True, y=True, alpha=0.3)
        # Make line thicker (width=2) and brighter blue
        self.raw_plot_widget.getAxis('left').setTickFont(self.larger_font) # Apply font to axis ticks
        self.raw_plot_curve = self.raw_plot_widget.plot(pen=pg.mkPen(color=(100, 100, 255), width=2))
        self.raw_time_cursor = pg.InfiniteLine(angle=90, movable=False, pen='r')
        self.raw_plot_widget.addItem(self.raw_time_cursor)

        self.filtered_plot_widget = pg.PlotWidget(title="Filtered Signal")
        self.filtered_plot_widget.setLabel('left', 'Amplitude')
        self.filtered_plot_widget.getAxis('left').setTickFont(self.larger_font) # Apply font to axis ticks
        self.filtered_plot_widget.setLabel('bottom', 'Time (s)', color='white') # Ensure label color matches foreground
        self.filtered_plot_widget.showGrid(x=True, y=True, alpha=0.3)
        self.filtered_plot_curve = self.filtered_plot_widget.plot(pen='g')
        self.filtered_time_cursor = pg.InfiniteLine(angle=90, movable=False, pen='r')
        self.filtered_plot_widget.addItem(self.filtered_time_cursor)

        # Link X axes
        self.filtered_plot_widget.setXLink(self.raw_plot_widget)
        # Apply font to bottom axis ticks (only need to set on one linked axis)
        self.filtered_plot_widget.getAxis('bottom').setTickFont(self.larger_font)

        # --- Timeline Scrubber ---
        self.timeline_slider = QSlider(Qt.Orientation.Horizontal)
        self.timeline_slider.setMinimum(0)
        self.timeline_slider.setMaximum(0) # Will be set when data loads
        self.timeline_slider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.timeline_slider.setTickInterval(10) # Example interval
        self.timeline_slider.sliderMoved.connect(self._slider_value_changed) # Update plots while dragging
        self.timeline_slider.sliderPressed.connect(self._pause_on_slider_press) # Pause playback on drag

        # --- Spectrum Plot ---
        self.spectrum_plot_widget = pg.PlotWidget(title="Frequency Spectrum")
        self.spectrum_plot_widget.setLabel('left', 'Magnitude')
        self.spectrum_plot_widget.setLabel('bottom', 'Frequency (Hz)', color='white')
        self.spectrum_plot_widget.showGrid(x=True, y=True, alpha=0.3)
        self.spectrum_plot_widget.getAxis('bottom').setTickFont(self.larger_font)
        self.spectrum_plot_widget.getAxis('left').setTickFont(self.larger_font)
        self.raw_spectrum_curve = self.spectrum_plot_widget.plot(pen=pg.mkPen(color=(100, 100, 255, 150), width=1.5), name="Raw") # Slightly transparent blue
        self.filtered_spectrum_curve = self.spectrum_plot_widget.plot(pen=pg.mkPen(color=(100, 255, 100, 150), width=1.5), name="Filtered") # Slightly transparent green
        # --- Add second curve for raw signal plot ---
        self.raw_plot_curve_alt = self.raw_plot_widget.plot(pen=pg.mkPen(color=(255, 165, 0, 200), width=2), name="Median/Mean") # Orange, slightly transparent
        # --- Add text item for peak frequency ---
        self.peak_freq_text = pg.TextItem(anchor=(0, 1), color=(255, 255, 0)) # Yellow text, top-left anchor
        self.spectrum_plot_widget.addItem(self.peak_freq_text)
        # --- End Plot Appearance Changes ---


        plot_layout.addWidget(self.raw_plot_widget)
        plot_layout.addWidget(self.filtered_plot_widget)
        plot_layout.addWidget(self.timeline_slider) # Add slider below main plots

        main_layout.addWidget(plot_widget_container, 3) # Give plots more space
        # --- Add Displacement Histogram Plot ---
        self.disp_histogram_widget = pg.PlotWidget(title="Live Vertical Displacement Histogram")
        self.disp_histogram_widget.setLabel('left', 'Count')
        self.disp_histogram_widget.setLabel('bottom', 'Vertical Displacement (pixels)', color='white')
        self.disp_histogram_widget.showGrid(x=True, y=True, alpha=0.3)
        self.disp_histogram_widget.getAxis('bottom').setTickFont(self.larger_font)
        self.disp_histogram_widget.getAxis('left').setTickFont(self.larger_font)
        # Initialize without data, stepMode will be handled by setData later
        self.disp_histogram_curve = pg.PlotCurveItem(pen='y', fillLevel=0, brush=(255,255,0,80))
        self.disp_histogram_widget.addItem(self.disp_histogram_curve)
        # --- Disable auto-ranging for histogram ---
        self.disp_histogram_widget.getViewBox().disableAutoRange()
        plot_layout.addWidget(self.spectrum_plot_widget) # Add spectrum plot below
        plot_layout.addWidget(self.disp_histogram_widget) # Add histogram plot at the bottom

        # --- Controls Area ---
        controls_container = QWidget()
        controls_container.setSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Preferred)
        controls_layout = QVBoxLayout(controls_container)

        # Playback Controls
        playback_group = QGroupBox("Playback")
        playback_layout = QGridLayout(playback_group) # Use grid for better alignment
        self.play_pause_button = QPushButton("Play")
        self.play_pause_button.setCheckable(True)
        self.play_pause_button.toggled.connect(self._toggle_playback)
        self.reset_button = QPushButton("Reset")
        self.reset_button.clicked.connect(self._reset_playback)

        # --- Playback Speed Control ---
        speed_label = QLabel("Speed:")
        speed_label.setFont(self.larger_font)
        self.speed_combo = QComboBox()
        self.speed_combo.addItems(["1x", "0.5x", "0.25x", "0.125x"])
        self.speed_combo.setFont(self.larger_font)
        self.speed_combo.currentIndexChanged.connect(self._update_playback_speed)
        # --- End Playback Speed Control ---
        # --- Frame Step Buttons ---
        self.prev_frame_button = QPushButton("<")
        self.prev_frame_button.clicked.connect(self._prev_frame)
        self.next_frame_button = QPushButton(">")
        self.next_frame_button.clicked.connect(self._next_frame)
        self.prev_frame_button.setFont(self.larger_font)
        self.next_frame_button.setFont(self.larger_font)

        playback_layout.addWidget(self.play_pause_button, 0, 0)
        playback_layout.addWidget(self.reset_button, 0, 1)
        playback_layout.addWidget(speed_label, 1, 0, Qt.AlignmentFlag.AlignRight)
        playback_layout.addWidget(self.speed_combo, 1, 1)
        controls_layout.addWidget(playback_group)
        # Apply font to group box title
        playback_layout.addWidget(self.prev_frame_button, 2, 0)
        playback_layout.addWidget(self.next_frame_button, 2, 1)
        playback_group.setFont(self.larger_font)

        # --- Profile Management ---
        profile_group = QGroupBox("Profile Management")
        profile_layout = QVBoxLayout(profile_group)
        self.load_profile_button = QPushButton("Load Profile...")
        self.save_profile_button = QPushButton("Save Profile As...")
        self.load_profile_button.clicked.connect(self._load_profile)
        self.save_profile_button.clicked.connect(self._save_profile_as)
        profile_h_layout = QHBoxLayout()
        profile_h_layout.addWidget(self.load_profile_button)
        profile_h_layout.addWidget(self.save_profile_button)
        profile_layout.addLayout(profile_h_layout)
        controls_layout.addWidget(profile_group)

        # --- Show Features Button ---
        self.show_features_button = QPushButton("Show Feature Plot")
        self.show_features_button.clicked.connect(self.feature_plot_window.show)
        controls_layout.addWidget(self.show_features_button)
        # --- Add PCA Window Button ---
        self.show_pca_button = QPushButton("Show PCA Vector Plot")
        self.show_pca_button.clicked.connect(self.pca_vector_window.show)
        controls_layout.addWidget(self.show_pca_button)
        # --- End PCA Window Button ---
        # --- End Show Features Button ---

        # Apply font to group box title
        profile_group.setFont(self.larger_font)
        # --- End Profile Management ---

        # Signal Generator Settings (Optional - if recalculating raw signal)
        sg_group = QGroupBox("Signal Generation")
        sg_layout = QFormLayout(sg_group)
        self.aggMethod_combo = QComboBox()
        self.aggMethod_combo.addItems(["median", "mean"])
        self.aggMethod_combo.setFont(self.larger_font) # Apply font
        self.recalc_raw_checkbox = QCheckBox("Recalculate Raw Signal")
        self.recalc_raw_checkbox.setToolTip("Recalculate raw signal from feature points using selected method.")
        self.recalc_raw_checkbox.setFont(self.larger_font) # Apply font
        self.recalc_raw_checkbox.setChecked(True) # Set to checked by default
        self.compare_agg_checkbox = QCheckBox("Compare Mean vs Median")
        self.compare_agg_checkbox.setToolTip("When recalculating, show both mean (blue) and median (orange) raw signals.")
        self.compare_agg_checkbox.setFont(self.larger_font) # Apply font
        # --- Add IQR Filter Controls ---
        self.iqr_filter_checkbox = QCheckBox("Enable IQR Outlier Filter")
        self.iqr_filter_checkbox.setFont(self.larger_font)
        self.iqr_k_spin = QDoubleSpinBox(minimum=0.5, maximum=5.0, singleStep=0.1, decimals=1, value=1.5)
        self.iqr_k_spin.setFont(self.larger_font)
        self.iqr_k_spin.setEnabled(False) # Disabled by default
        self.iqr_filter_checkbox.toggled.connect(self.iqr_k_spin.setEnabled) # Enable/disable spinbox with checkbox
        # --- End IQR Filter Controls ---

        sg_layout.addRow(self.recalc_raw_checkbox)
        sg_agg_label = QLabel("Aggregation:") # Create label explicitly
        sg_agg_label.setFont(self.larger_font) # Apply font
        sg_layout.addRow(sg_agg_label, self.aggMethod_combo)
        controls_layout.addWidget(sg_group)
        # Apply font to group box title
        sg_group.setFont(self.larger_font)
        sg_layout.addRow(self.iqr_filter_checkbox) # Add IQR checkbox
        sg_layout.addRow("IQR k-factor:", self.iqr_k_spin) # Add IQR spinbox
        sg_layout.addRow(self.compare_agg_checkbox) # Add the checkbox to the layout

        # Signal Processor Settings
        sp_group = QGroupBox("Signal Processing")
        sp_layout = QFormLayout(sp_group)
        self.filtLow_spin = QDoubleSpinBox(minimum=0.05, maximum=1.00, singleStep=0.01, decimals=2, value=0.1)
        self.filtHigh_spin = QDoubleSpinBox(minimum=0.10, maximum=5.00, singleStep=0.05, decimals=2, value=1.0)
        self.filtLow_spin.setFont(self.larger_font) # Apply font
        self.filtHigh_spin.setFont(self.larger_font) # Apply font
        self.filtType_combo = QComboBox()
        self.filtType_combo.addItems(["lfilter", "filtfilt"])
        self.filtType_combo.setFont(self.larger_font) # Apply font
        self.peakProm_spin = QDoubleSpinBox(minimum=0.0, maximum=10.0, singleStep=0.005, value=0.0, decimals=3)
        self.peakProm_spin.setFont(self.larger_font) # Apply font

        self.filtLow_spin.setToolTip("Lower cutoff frequency (Hz) for bandpass filter.")
        self.filtHigh_spin.setToolTip("Upper cutoff frequency (Hz) for bandpass filter.")
        self.filtType_combo.setToolTip("Filter method: lfilter (causal) or filtfilt (zero-phase).")
        self.peakProm_spin.setToolTip("Minimum peak prominence for peak detection (0 = disabled).")

        sp_layout.addRow("Filter Low (Hz):", self.filtLow_spin)
        sp_layout.addRow("Filter High (Hz):", self.filtHigh_spin)
        sp_layout.addRow("Filter Method:", self.filtType_combo)
        sp_peak_label = QLabel("Peak Prominence:") # Create label explicitly
        sp_peak_label.setFont(self.larger_font) # Apply font
        sp_layout.addRow(sp_peak_label, self.peakProm_spin)
        controls_layout.addWidget(sp_group)
        # Apply font to group box title
        sp_group.setFont(self.larger_font)
        # Apply font to form layout labels (requires iterating or explicit creation)
        # Explicit creation is safer if layout changes
        sp_layout.labelForField(self.filtLow_spin).setFont(self.larger_font)
        sp_layout.labelForField(self.filtHigh_spin).setFont(self.larger_font)
        sp_layout.labelForField(self.filtType_combo).setFont(self.larger_font)

                # --- Spectrum Analyzer Settings ---
        sa_group = QGroupBox("Spectrum Analyzer")
        sa_layout = QFormLayout(sa_group)
        self.fft_window_size_combo = QComboBox()
        # Populate with powers of 2, relative to sampling rate? Or fixed sizes? Let's use fixed sizes for now.
        self.fft_window_size_combo.addItems(["256", "512", "1024", "2048", "4096"])
        self.fft_window_size_combo.setCurrentText("1024")
        self.fft_window_size_combo.setFont(self.larger_font)
        self.fft_window_type_combo = QComboBox()
        self.fft_window_type_combo.addItems(["hann", "hamming", "blackman", "boxcar"]) # Common window types
        self.fft_window_type_combo.setCurrentText("hann")
        self.fft_window_type_combo.setFont(self.larger_font)
        self.plot_raw_spectrum_check = QCheckBox("Plot Raw Spectrum")
        self.plot_raw_spectrum_check.setChecked(False)
        self.plot_raw_spectrum_check.setFont(self.larger_font)
        self.plot_filtered_spectrum_check = QCheckBox("Plot Filtered Spectrum")
        self.plot_filtered_spectrum_check.setChecked(True) # Default to showing filtered
        self.plot_filtered_spectrum_check.setFont(self.larger_font)
        # --- New Spectrum Controls ---
        self.fft_padding_combo = QComboBox()
        self.fft_padding_combo.addItems(["None", "2x", "4x", "8x", "8192"]) # Padding options
        self.fft_padding_combo.setCurrentText("None")
        self.fft_padding_combo.setFont(self.larger_font)
        self.db_scale_check = QCheckBox("dB Scale")
        self.db_scale_check.setFont(self.larger_font)
        self.show_peak_freq_check = QCheckBox("Show Peak Freq (0.1-1.5Hz)")
        self.show_peak_freq_check.setChecked(True)
        self.show_peak_freq_check.setFont(self.larger_font)
        # --- End New Spectrum Controls ---
        sa_layout.addRow("FFT Window Size:", self.fft_window_size_combo)
        sa_layout.addRow("FFT Window Type:", self.fft_window_type_combo)
        sa_layout.addRow("Padding:", self.fft_padding_combo)
        sa_layout.addRow(self.db_scale_check) # Add dB Scale checkbox
        sa_layout.addRow(self.plot_raw_spectrum_check, self.plot_filtered_spectrum_check) # Combine checkboxes
        # --- Add Histogram Controls ---
        self.hist_bins_spin = QSpinBox(minimum=5, maximum=100, value=20)
        self.hist_bins_spin.setFont(self.larger_font)
        sa_layout.addRow("Hist Bins:", self.hist_bins_spin)
        controls_layout.addWidget(sa_group)
        sa_group.setFont(self.larger_font)
        # --- End Spectrum Analyzer Settings ---


        # Apply Button
        self.apply_button = QPushButton("Apply Settings & Reprocess")
        self.apply_button.clicked.connect(self._reprocess_data)
        controls_layout.addWidget(self.apply_button)

        controls_layout.addStretch(1) # Push controls to the top
        main_layout.addWidget(controls_container, 1) # Give controls less space

        # Connect signals for automatic reprocessing (optional, can rely on button)
        # self.aggMethod_combo.currentIndexChanged.connect(self._reprocess_data)
        # self.recalc_raw_checkbox.stateChanged.connect(self._reprocess_data)
        # self.filtLow_spin.valueChanged.connect(self._reprocess_data)
        # self.filtHigh_spin.valueChanged.connect(self._reprocess_data)
        # self.filtType_combo.currentIndexChanged.connect(self._reprocess_data)
        # self.peakProm_spin.valueChanged.connect(self._reprocess_data)

    def load_data(self, file_path):
        """Loads data from the specified .npz file."""
        print(f"Loading data from: {file_path}")
        try:
            with np.load(file_path, allow_pickle=True) as data:
                if 'timestamps' not in data or 'raw_signal' not in data or 'feature_coords' not in data:
                    raise KeyError("NPZ file missing one or more required keys: 'timestamps', 'raw_signal', 'feature_coords'")

                self.timestamps = data['timestamps']
                self.raw_signal_loaded = data['raw_signal']
                self.feature_coords = data['feature_coords'] # List/array of (N, 2) arrays

                if len(self.timestamps) < 2:
                    print("Warning: Not enough timestamps to calculate sampling rate. Using default.")
                    self.sampling_rate = 30.0
                else:
                    # Calculate average sampling rate from timestamps
                    intervals = np.diff(self.timestamps)
                    mean_interval = np.mean(intervals)
                    if mean_interval > 1e-6:
                        self.sampling_rate = 1.0 / mean_interval
                    else:
                        print("Warning: Mean time interval is near zero. Using default sampling rate.")
                        self.sampling_rate = 30.0

                print(f"Data loaded successfully. Frames: {len(self.timestamps)}, Sampling Rate: {self.sampling_rate:.2f} Hz")
                self.raw_signal_processed = self.raw_signal_loaded.copy() # Start with loaded raw signal
                # --- Pass data to feature window ---
                self.feature_plot_window.set_data(self.timestamps, self.feature_coords)

        except FileNotFoundError:
            # --- Clear slider on error ---
            self.timeline_slider.setMaximum(0)
            print(f"Error: Recording file not found at {file_path}")
            QApplication.quit()
        except Exception as e:
            print(f"Error loading or processing NPZ file: {e}")
            traceback.print_exc()
            QApplication.quit()

        # --- Set slider range after loading data ---
        if self.timestamps is not None:
            max_index = len(self.timestamps) - 1
            self.timeline_slider.setMaximum(max_index if max_index >= 0 else 0)
            # Adjust tick interval based on data length
            tick_interval = max(1, max_index // 20) # Aim for ~20 ticks
            self.timeline_slider.setTickInterval(tick_interval)
    def _apply_settings(self):
        """Reads UI controls and re-initializes processing components."""
        print("Applying settings...")
        sg_config = {
            'SIGNAL_AGGREGATION_METHOD': self.aggMethod_combo.currentText(),
            'IQR_FILTER_ENABLED': self.iqr_filter_checkbox.isChecked(), # Read IQR checkbox
            'IQR_K_FACTOR': self.iqr_k_spin.value() # Read IQR spinbox
        }
        sp_config = {
            'SIGNAL_FILTER_LOW_HZ': self.filtLow_spin.value(),
            'SIGNAL_FILTER_HIGH_HZ': self.filtHigh_spin.value(),
            'SIGNAL_FILTER_METHOD': self.filtType_combo.currentText(),
            'PEAK_DETECT_PROMINENCE': self.peakProm_spin.value() if self.peakProm_spin.value() > 1e-6 else None
        }

        try:
            self.signal_generator = SignalGenerator(config=sg_config)
            self.signal_processor = SignalProcessor(config=sp_config, sampling_rate=self.sampling_rate)
            print("SignalGenerator and SignalProcessor re-initialized.")
        except Exception as e:
            print(f"Error re-initializing components: {e}")
            traceback.print_exc()

    def _gather_settings_from_ui(self):
        """Gathers current settings from UI widgets into a dictionary."""
        # Note: Optical flow params are not configurable in this tuner UI
        settings = {
            'feature_tracker': { # Keep FT section for structure consistency, but empty
                'OPTICAL_FLOW_PARAMS': {}
            },
            # Signal Generator settings remain the same
            'signal_generator': {
                'SIGNAL_AGGREGATION_METHOD': self.aggMethod_combo.currentText(),
                'IQR_FILTER_ENABLED': self.iqr_filter_checkbox.isChecked(), # Save IQR state
                'IQR_K_FACTOR': self.iqr_k_spin.value() # Save IQR k-factor
            },
            'signal_processor': {
                'SIGNAL_FILTER_LOW_HZ': self.filtLow_spin.value(),
                'SIGNAL_FILTER_HIGH_HZ': self.filtHigh_spin.value(),
                'SIGNAL_FILTER_METHOD': self.filtType_combo.currentText(),
                'PEAK_DETECT_PROMINENCE': self.peakProm_spin.value() if self.peakProm_spin.value() > 1e-6 else None
            }
        }
        return settings

    def _populate_ui_from_settings(self, settings_dict):
        """Populates UI widgets from a settings dictionary."""
        print("[UI] Populating settings widgets from loaded profile.")
        # --- Default empty dicts ---
        ft_settings = settings_dict.get('feature_tracker', {})
        sg_settings = settings_dict.get('signal_generator', {})
        sp_settings = settings_dict.get('signal_processor', {})
        try:
            # Populate Signal Generator widgets (no FT widgets to populate)
            agg_method = sg_settings.get('SIGNAL_AGGREGATION_METHOD', 'median')
            self.aggMethod_combo.setCurrentText(agg_method)
            # --- Populate IQR Filter Widgets ---
            iqr_enabled = sg_settings.get('IQR_FILTER_ENABLED', False)
            self.iqr_filter_checkbox.setChecked(iqr_enabled)
            self.iqr_k_spin.setValue(sg_settings.get('IQR_K_FACTOR', 1.5))
            self.iqr_k_spin.setEnabled(iqr_enabled) # Ensure spinbox state matches checkbox

            # Populate Signal Processor widgets
            self.filtLow_spin.setValue(sp_settings.get('SIGNAL_FILTER_LOW_HZ', 0.1))
            self.filtHigh_spin.setValue(sp_settings.get('SIGNAL_FILTER_HIGH_HZ', 1.0))
            filt_method = sp_settings.get('SIGNAL_FILTER_METHOD', 'lfilter')
            self.filtType_combo.setCurrentText(filt_method)
            prominence = sp_settings.get('PEAK_DETECT_PROMINENCE')
            self.peakProm_spin.setValue(prominence if prominence is not None else 0.0)

            print("[UI] Settings widgets populated.")

        except Exception as e:
            print(f"Error populating settings widgets: {e}")
            traceback.print_exc()
            QMessageBox.warning(self, "Settings Error", f"Could not fully populate settings widgets from profile:\n{e}")

    @pyqtSlot()
    def _load_profile(self):
        """Opens dialog to load settings from a JSON profile."""
        filePath, _ = QFileDialog.getOpenFileName(
            self, "Load Profile", DEFAULT_RECORDING_DIR, "JSON Files (*.json)"
        )
        if filePath:
            try:
                with open(filePath, 'r') as f:
                    loaded_settings = json.load(f)
                self._populate_ui_from_settings(loaded_settings)
                self._reprocess_data() # Reprocess with newly loaded settings
                print(f"Profile loaded successfully from: {filePath}")
            except Exception as e:
                print(f"Error loading profile: {e}")
                QMessageBox.critical(self, "Load Error", f"Failed to load profile:\n{filePath}\n\n{e}")

    def _calculate_spectrum(self, signal_data, window_size, window_type, padding_option="None", use_db_scale=False):
        """Calculates the frequency spectrum of the given signal data."""
        if signal_data is None or len(signal_data) < 2: # Need at least 2 points for FFT
            return None, None, None # Freq, Mag, Peak Freq

        # --- Adjust window size if it exceeds data length ---
        actual_window_size = min(window_size, len(signal_data))
        if actual_window_size != window_size:
            print(f"[Spectrum Debug] Warning: Requested FFT window size ({window_size}) > data length ({len(signal_data)}). Using {actual_window_size}.")

        # --- Use actual_window_size --- # Corrected comment, was using window_size before
        segment = signal_data[-actual_window_size:] # Use adjusted size
        # Apply window function
        try:
            window_func = getattr(scipy_signal.windows, window_type)
            window = window_func(actual_window_size) # Use adjusted size
            segment = segment * window
        except AttributeError:
            print(f"Warning: Unknown window type '{window_type}'. Using boxcar (no window).")
        except Exception as e:
            print(f"Error applying window function: {e}")
            # Continue without windowing

        # --- Determine FFT size with padding ---
        n_fft = actual_window_size
        if padding_option == "None":
            n_fft = actual_window_size
        elif padding_option.endswith('x'):
            try:
                factor = int(padding_option.replace('x', ''))
                n_fft = actual_window_size * factor
            except ValueError: pass # Keep original size if parse fails
        elif padding_option.isdigit():
            n_fft = max(actual_window_size, int(padding_option)) # Use larger of window or specified padding

        # Calculate FFT
        fft_result = np.fft.fft(segment, n=n_fft) # Apply padding here
        # Calculate frequencies using adjusted size
        frequencies = np.fft.fftfreq(n_fft, d=1.0/self.sampling_rate) # Use n_fft for frequencies

        # Get magnitude and keep only positive frequencies (adjust mask size)
        magnitude = np.abs(fft_result)
        positive_mask = frequencies >= 0
        frequencies_pos = frequencies[positive_mask]
        magnitude_pos = magnitude[positive_mask]

        # Normalize magnitude (optional, e.g., divide by window size)
        magnitude_pos = magnitude_pos / actual_window_size # Use adjusted size for normalization

        # --- Convert to dB if requested ---
        if use_db_scale:
            # Add small epsilon to prevent log(0)
            magnitude_db = 20 * np.log10(magnitude_pos + 1e-12)
            magnitude_to_return = magnitude_db
        else:
            magnitude_to_return = magnitude_pos

        # --- Find Peak Frequency ---
        peak_freq_hz = None
        try:
            # Define typical respiration frequency range
            min_resp_hz = 0.1
            max_resp_hz = 1.5
            valid_range_mask = (frequencies_pos >= min_resp_hz) & (frequencies_pos <= max_resp_hz)
            if np.any(valid_range_mask):
                # Use linear magnitude (magnitude_pos) for finding the peak index, regardless of dB display
                peak_index_in_range = np.argmax(magnitude_pos[valid_range_mask])
                peak_freq_hz = frequencies_pos[valid_range_mask][peak_index_in_range]
        except Exception as e_peak: print(f"Error finding peak frequency: {e_peak}")
        return frequencies_pos, magnitude_to_return, peak_freq_hz


    @pyqtSlot()
    def _reprocess_data(self):
        """Applies current settings and reprocesses the entire dataset."""
        if self.timestamps is None:
            print("No data loaded to reprocess.")
            return

        print("Reprocessing all data...")
        self._apply_settings() # Re-init components with current settings

        if self.signal_generator is None or self.signal_processor is None:
            print("Processing components not initialized.")
            return

        # --- Recalculate Raw Signal (Optional) ---
        if self.recalc_raw_checkbox.isChecked():
            print("Recalculating raw signal from feature coordinates...")
            if self.feature_coords is None or len(self.feature_coords) != len(self.timestamps):
                print("Error: Feature coordinate data is missing or length mismatch.")
                return

        # --- Recalculate Raw Signal using SignalGenerator (Optional) ---
        if self.recalc_raw_checkbox.isChecked():
            print("Recalculating raw signal using SignalGenerator...")
            if self.feature_coords is None or len(self.feature_coords) != len(self.timestamps):
                print("Error: Feature coordinate data is missing or length mismatch for recalculation.")
                return

            # --- Prepare data for SignalGenerator and Histogram ---
            tracked_data_list = []
            all_displacements_per_frame = [] # Store displacements for histogram
            # --- IMPORTANT LIMITATION ---
            # The .npz file does NOT contain quality scores. Therefore, the recalculation
            # here CANNOT simulate the effect of quality weighting. We pass None for qualities.
            for i in range(len(self.feature_coords) - 1):
                old_p = self.feature_coords[i]
                new_p = self.feature_coords[i+1]
                tracked_data_list.append((old_p, new_p, None)) # Pass None for qualities

                # Basic matching by index (crude approximation)
                min_len = min(len(old_p) if old_p is not None else 0, len(new_p) if new_p is not None else 0)
                if min_len > 0:
                    old_p_2d = old_p[:min_len].reshape(-1, 2)
                    new_p_2d = new_p[:min_len].reshape(-1, 2)
                    displacements = new_p_2d[:, 1] - old_p_2d[:, 1] # Y_new - Y_old
                    all_displacements_per_frame.append(displacements) # Store for histogram
                else:
                    all_displacements_per_frame.append(np.array([])) # Empty array for this frame

            # Add empty data for the last frame (no displacement)
            tracked_data_list.append((self.feature_coords[-1], self.feature_coords[-1], None)) # Dummy pair, None qualities
            all_displacements_per_frame.append(np.array([])) # Empty for last frame

            # Store displacements for live histogram update
            self._live_displacements = all_displacements_per_frame
            self._calculate_and_set_histogram_ranges()

            # --- Use the configured SignalGenerator ---
            # Note: self.signal_generator was already initialized in _apply_settings()
            recalculated_primary_signal = self.signal_generator.process_tracked_features(tracked_data_list)
            # Apply inversion (as done in pipeline_manager)
            self.raw_signal_processed = -np.array(recalculated_primary_signal)
            print(f"Raw signal recalculated using SignalGenerator ({self.signal_generator.aggregation_method}, IQR: {self.signal_generator.iqr_filter_enabled}).")

            # --- Handle Compare Mode ---
            compare_mode = self.compare_agg_checkbox.isChecked()
            if compare_mode:
                # Create a temporary generator with the *opposite* aggregation method
                # but the same IQR settings
                primary_method = self.signal_generator.aggregation_method
                alt_method = 'median' if primary_method == 'mean' else 'mean'
                alt_sg_config = {
                    'SIGNAL_AGGREGATION_METHOD': alt_method,
                    'IQR_FILTER_ENABLED': self.signal_generator.iqr_filter_enabled,
                    'IQR_K_FACTOR': self.signal_generator.iqr_k_factor,
                    'SIGNAL_MIN_FEATURES_FOR_SIGNAL': self.signal_generator.min_features_for_signal
                }
                try:
                    alt_signal_generator = SignalGenerator(config=alt_sg_config)
                    recalculated_alt_signal = alt_signal_generator.process_tracked_features(tracked_data_list)
                    # Apply inversion
                    self.raw_signal_alt_processed = -np.array(recalculated_alt_signal)
                    print(f"Alternative raw signal recalculated using SignalGenerator ({alt_method}, IQR: {alt_sg_config['IQR_FILTER_ENABLED']}).")
                except Exception as e_alt:
                    print(f"Error creating/using alternative SignalGenerator: {e_alt}")
                    self.raw_signal_alt_processed = None
            else:
                self.raw_signal_alt_processed = None # No alternative signal

            # --- End Recalculation ---

        else:
            # --- Ensure alt signal and displacements are None when not recalculating ---
            # --- This block runs if checkbox is NOT checked ---
            self.raw_signal_processed = self.raw_signal_loaded.copy()
            self.raw_signal_alt_processed = None # No alternative signal
            # --- Clear histogram ranges if not recalculating ---
            self._clear_histogram_ranges()
            self._live_displacements = None # No live displacements available
            print("Using loaded raw signal.")

        # --- Process Raw Signal ---
        print("Processing raw signal with SignalProcessor...")
        # Resetting is not needed as SignalProcessor is re-initialized in _apply_settings()
        # self.signal_processor.reset()
        # Process the entire raw signal history
        # --- MODIFIED: Process signal value by value ---
        processed_filtered_signal = []
        for raw_value in self.raw_signal_processed:
            self.signal_processor.process_signal_values([raw_value]) # Pass as a list containing one value
            processed_filtered_signal.append(self.signal_processor.get_latest_filtered_value())
        self.filtered_signal_processed = np.array(processed_filtered_signal)
        print(f"Signal processed ({len(self.filtered_signal_processed)} filtered points).")

        # --- Update Plots ---
        valid_timestamps = self.timestamps[:len(self.raw_signal_processed)] # Match length
        self.raw_plot_curve.setData(valid_timestamps, self.raw_signal_processed)
        # --- Update alt raw curve if needed ---
        if self.raw_signal_alt_processed is not None:
            self.raw_plot_curve_alt.setData(valid_timestamps, self.raw_signal_alt_processed)
        else:
            self.raw_plot_curve_alt.clear() # Clear if not comparing

        self.filtered_plot_curve.setData(valid_timestamps, self.filtered_signal_processed)
        print("Plots updated.")


        self._reset_playback() # Reset cursor position after reprocessing

    def _calculate_and_set_histogram_ranges(self):
        """Calculates and sets fixed X/Y ranges for the histogram based on all frames."""
        if self._live_displacements is None:
            self._clear_histogram_ranges()
            return

        try:
            # Flatten all valid, finite displacements
            # --- MODIFIED: Add checks for type and numeric dtype ---
            all_disp_flat = np.concatenate([
                d[np.isfinite(d)] for d in self._live_displacements
                if isinstance(d, np.ndarray) # Check if it's a numpy array
                and np.issubdtype(d.dtype, np.number) # Check if dtype is numeric
                and d.size > 0 # Check if not empty
            ])

            if all_disp_flat.size == 0:
                print("[Hist Range] No valid displacement data found to calculate ranges.")
                self._clear_histogram_ranges()
                return

            # Calculate X range (Displacement)
            min_disp, max_disp = np.min(all_disp_flat), np.max(all_disp_flat)
            padding_x = (max_disp - min_disp) * 0.05 # 5% padding
            self.hist_x_range = (min_disp - padding_x, max_disp + padding_x)

            # Calculate Y range (Max Count)
            num_bins = self.hist_bins_spin.value()
            max_y_count = 0
            # Use the calculated fixed X range for consistent binning across frames
            hist_range_param = (self.hist_x_range[0], self.hist_x_range[1])
            for frame_displacements in self._live_displacements:
                if frame_displacements is not None and frame_displacements.size > 0:
                    finite_disp = frame_displacements[np.isfinite(frame_displacements)]
                    if finite_disp.size > 0:
                        hist_y, _ = np.histogram(finite_disp, bins=num_bins, range=hist_range_param)
                        max_y_count = max(max_y_count, np.max(hist_y) if hist_y.size > 0 else 0)

            self.hist_y_range = (0, max_y_count * 1.1) # 10% padding on top

            # Apply ranges to the plot
            self.disp_histogram_widget.setXRange(*self.hist_x_range, padding=0)
            self.disp_histogram_widget.setYRange(*self.hist_y_range, padding=0)
            print(f"[Hist Range] Set X range: {self.hist_x_range}, Y range: {self.hist_y_range}")
        except Exception as e:
            print(f"Error calculating histogram ranges: {e}")
            self._clear_histogram_ranges() # Clear ranges on error

    def _clear_histogram_ranges(self):
        """Clears stored histogram ranges and potentially resets plot ranges."""
        self.hist_x_range = None
        self.hist_y_range = None
        # Optionally reset plot ranges or let autoRange take over if re-enabled
        # self.disp_histogram_widget.enableAutoRange() # Or set to default ranges
        self.disp_histogram_curve.clear() # Clear data when ranges are invalid
        print("[Hist Range] Cleared histogram ranges.")

    @pyqtSlot(bool)
    def _toggle_playback(self, checked):
        """Starts or stops the playback timer."""
        if checked:
            if self.timestamps is not None and len(self.timestamps) > 0:
                self.is_playing = True
                self.play_pause_button.setText("Pause")
                # --- Adjust start time based on speed ---
                self.playback_start_time = time.time() - (self.timestamps[self.current_frame_index] - self.timestamps[0]) / self.playback_speed
                self.playback_timer.start(30) # Update cursor roughly 30 times/sec
                print("Playback started.")
        else:
            self.is_playing = False
            self.play_pause_button.setText("Play")
            self.playback_timer.stop()
            print("Playback paused.")

    @pyqtSlot(int)
    def _update_playback_speed(self, index):
        """Updates the playback speed multiplier based on combo box selection."""
        speed_text = self.speed_combo.itemText(index) # e.g., "0.5x"
        try:
            new_speed = float(speed_text.replace('x', ''))
            if self.is_playing:
                # Adjust start time to maintain current playback position
                current_simulated_time = (time.time() - self.playback_start_time) * self.playback_speed
                self.playback_start_time = time.time() - current_simulated_time / new_speed
            self.playback_speed = new_speed
            print(f"Playback speed set to: {self.playback_speed}x")
        except ValueError:
            self.playback_speed = 1.0 # Default to 1x on error

    @pyqtSlot()
    def _reset_playback(self):
        """Resets the playback cursor to the beginning."""
        self.current_frame_index = 0
        self._update_plots_for_frame(self.current_frame_index) # Update all plots for frame 0
        if self.is_playing:
            # If playing, reset the timer baseline to effectively restart from 0
            # If paused, just setting the index is enough
            self.playback_start_time = time.time() # Reset timer baseline
        print("Playback reset.")

    def _update_histogram_plot(self):
        """Updates the displacement histogram for the current frame."""
        hist_x, hist_y = None, None # Initialize histogram data
        displacements = None # Initialize displacements to None

        try: # Outer try for initial checks
            if self._live_displacements is None or not (0 <= self.current_frame_index < len(self._live_displacements)):
                # --- DEBUG PRINT ---
                print(f"[Hist Debug] Clearing histogram. _live_displacements is None: {self._live_displacements is None}, Index valid: {0 <= self.current_frame_index < (len(self._live_displacements) if self._live_displacements is not None else 0)}")
                # displacements remains None
            else:
                # --- This block executes only if _live_displacements is valid ---
                displacements = self._live_displacements[self.current_frame_index] # Get displacements for current frame

            # Now, check the assigned (or None) displacements variable
            if displacements is not None and len(displacements) > 0:
                # --- FIX: Ensure displacements is a numeric array before using np.isfinite ---
                try:
                    # Attempt conversion to float, handling potential errors
                    numeric_displacements = np.asarray(displacements, dtype=float)
                except (ValueError, TypeError) as e_conv:
                    print(f"[Hist Debug] Warning: Could not convert displacements to numeric array: {e_conv}")
                    numeric_displacements = np.array([], dtype=float) # Use empty array on conversion failure

                # Ensure displacements are finite before histogram calculation
                finite_displacements = numeric_displacements[np.isfinite(numeric_displacements)]
                if len(finite_displacements) > 0:
                    num_bins = self.hist_bins_spin.value() # Use the UI value for bin count
                    # Calculate histogram
                    hist_y, hist_x = np.histogram(finite_displacements, bins=num_bins) # hist_x has len(hist_y)+1
                    # --- DEBUG PRINT ---
                    # print(f"[Hist Debug] Frame {self.current_frame_index}: Calculated hist_y (counts) = {hist_y}, hist_x (edges) = {hist_x}")
                else:
                    # --- DEBUG PRINT ---
                    print("[Hist Debug] No finite displacements to create histogram.")
                    # hist_x, hist_y remain None
            else:
                # --- DEBUG PRINT ---
                if displacements is None:
                     print("[Hist Debug] Displacements variable is None (likely due to invalid index or missing data).")
                # hist_x, hist_y remain None
        except Exception as e_hist_outer: # Catch errors during data access/checks
            print(f"Error preparing histogram data: {e_hist_outer}")
            traceback.print_exc() # Print traceback for unexpected errors
            self.disp_histogram_curve.setData([], []) # Clear on error
            return # Exit if data prep failed

        try: # Inner try specifically for histogram calculation and plotting
            # Check if histogram data is valid before plotting
            if hist_x is not None and hist_y is not None and len(hist_x) == len(hist_y) + 1:
                 # --- DEBUG PRINT ---
                # print(f"[Hist Debug] Attempting setData with hist_x shape {hist_x.shape}, hist_y shape {hist_y.shape}")
                 # Ensure data types are suitable for isfinite check later (should be by default from np.histogram)
                hist_x = np.asanyarray(hist_x, dtype=float)
                hist_y = np.asanyarray(hist_y, dtype=float)
                # Set stepMode here when setting data
                self.disp_histogram_curve.setData(hist_x, hist_y, stepMode="center") # Correctly applying stepMode here
            else:
                # Clear plot if data is invalid or empty
                # --- DEBUG PRINT ---
                # print(f"[Hist Debug] Clearing plot because hist_x or hist_y is invalid. hist_x is None: {hist_x is None}, hist_y is None: {hist_y is None}")
                self.disp_histogram_curve.setData([], [])
        except Exception as e_hist_plot: # Catch errors during setData or potential issues with hist data
            print(f"Error updating histogram plot (setData): {e_hist_plot}") # Use e_hist_plot here
            traceback.print_exc() # Print traceback for unexpected errors
            self.disp_histogram_curve.setData([], []) # Clear on error


    def _update_playback_cursor(self):
        """Updates the position of the time cursor based on simulated time."""
        if not self.is_playing or self.timestamps is None or len(self.timestamps) < 2:
            return

        # --- Incorporate playback speed ---
        elapsed_real_time = time.time() - self.playback_start_time
        elapsed_simulated_time = elapsed_real_time * self.playback_speed
        target_timestamp = self.timestamps[0] + elapsed_simulated_time

        # Find the closest frame index
        # Use searchsorted for efficiency
        new_frame_index = np.searchsorted(self.timestamps, target_timestamp, side='right') - 1
        new_frame_index = max(0, new_frame_index) # Ensure non-negative

        # Loop playback
        if new_frame_index >= len(self.timestamps) - 1:
            new_frame_index = 0
            # Reset timer baseline accounting for speed
            self.playback_start_time = time.time()

        # Update only if the index actually changed to avoid redundant calculations
        # and prevent unnecessary updates when looping back to 0
        if new_frame_index != self.current_frame_index:
            # Call the central plot update function
            self._update_plots_for_frame(new_frame_index)

    def _update_plots_for_frame(self, frame_index):
        """Updates time cursors, feature plot, histogram, and spectrum for a specific frame."""
        if self.timestamps is None or not (0 <= frame_index < len(self.timestamps)):
            print(f"[Plot Update] Invalid frame index: {frame_index}")
            return

        self.current_frame_index = frame_index
        current_time = self.timestamps[self.current_frame_index]

        # Update cursor positions
        self.raw_time_cursor.setPos(current_time)
        self.filtered_time_cursor.setPos(current_time)

        # Update feature plot window
        self.feature_plot_window.update_plot(self.current_frame_index)

        # --- Update PCA Vector Window ---
        # Need old and new points for the current transition
        old_pca_points, new_pca_points = None, None
        if self.feature_coords is not None:
            if self.current_frame_index > 0: # Need previous frame for old points
                old_pca_points = self.feature_coords[self.current_frame_index - 1]
            if self.current_frame_index < len(self.feature_coords): # Current frame for new points
                new_pca_points = self.feature_coords[self.current_frame_index]
        # Pass the relevant points to the PCA window
        self.pca_vector_window.update_plot(self.current_frame_index, old_pca_points, new_pca_points)
        # --- End PCA Vector Window Update ---



        # Update timeline slider position (block signals to prevent loop)
        self.timeline_slider.blockSignals(True)
        self.timeline_slider.setValue(self.current_frame_index)
        self.timeline_slider.blockSignals(False)
        # Update displacement histogram
        self._update_histogram_plot()

        # Update Spectrum Plot (using the same logic as in _update_playback_cursor)
        try:
            fft_win_size = int(self.fft_window_size_combo.currentText())
            fft_win_type = self.fft_window_type_combo.currentText()
            padding_opt = self.fft_padding_combo.currentText()
            use_db = self.db_scale_check.isChecked()

            start_index = max(0, self.current_frame_index + 1 - fft_win_size)
            end_index = self.current_frame_index + 1

            self.raw_spectrum_curve.clear()
            self.filtered_spectrum_curve.clear()

            peak_freq_raw, peak_freq_filt = None, None

            if self.plot_raw_spectrum_check.isChecked() and self.raw_signal_processed is not None:
                raw_segment = self.raw_signal_processed[start_index:end_index]
                freq_raw, mag_raw, peak_freq_raw = self._calculate_spectrum(raw_segment, fft_win_size, fft_win_type, padding_opt, use_db)
                if freq_raw is not None: self.raw_spectrum_curve.setData(freq_raw, mag_raw)

            if self.plot_filtered_spectrum_check.isChecked() and self.filtered_signal_processed is not None:
                filtered_segment = self.filtered_signal_processed[start_index:end_index]
                freq_filt, mag_filt, peak_freq_filt = self._calculate_spectrum(filtered_segment, fft_win_size, fft_win_type, padding_opt, use_db)
                if freq_filt is not None: self.filtered_spectrum_curve.setData(freq_filt, mag_filt)

            if self.show_peak_freq_check.isChecked():
                peak_text = ""
                if peak_freq_filt is not None and self.plot_filtered_spectrum_check.isChecked(): peak_text = f"Peak (Filt): {peak_freq_filt:.2f} Hz ({peak_freq_filt*60:.1f} BPM)"
                elif peak_freq_raw is not None and self.plot_raw_spectrum_check.isChecked(): peak_text = f"Peak (Raw): {peak_freq_raw:.2f} Hz ({peak_freq_raw*60:.1f} BPM)"
                self.peak_freq_text.setText(peak_text)
            else: self.peak_freq_text.setText("")
        except Exception as e_spec_update:
            print(f"Error updating spectrum for frame {frame_index}: {e_spec_update}")

    @pyqtSlot()
    def _save_profile_as(self):
        """Opens dialog to save current UI settings to a JSON profile."""
        filePath, _ = QFileDialog.getSaveFileName(
            self, "Save Profile As...", DEFAULT_RECORDING_DIR, "JSON Files (*.json)"
        )
        if filePath:
            if not filePath.lower().endswith('.json'):
                filePath += '.json'

            current_settings = self._gather_settings_from_ui()
            try:
                with open(filePath, 'w') as f:
                    json.dump(current_settings, f, indent=4)
                print(f"Profile saved successfully to: {filePath}")
                QMessageBox.information(self, "Save Successful", f"Settings saved to:\n{filePath}")
            except Exception as e:
                print(f"Error saving profile: {e}")
                QMessageBox.critical(self, "Save Error", f"Failed to save profile:\n{filePath}\n\n{e}")

    @pyqtSlot()
    def _prev_frame(self):
        """Steps to the previous frame."""
        if self.timestamps is None or len(self.timestamps) == 0: return
        if self.is_playing: # Pause if playing
            self.play_pause_button.setChecked(False) # This triggers _toggle_playback

        new_index = max(0, self.current_frame_index - 1)
        if new_index != self.current_frame_index:
            self._update_plots_for_frame(new_index)
            print(f"Stepped back to frame {new_index}")

    @pyqtSlot()
    def _next_frame(self):
        """Steps to the next frame."""
        if self.timestamps is None or len(self.timestamps) == 0: return
        if self.is_playing: # Pause if playing
            self.play_pause_button.setChecked(False) # This triggers _toggle_playback

        new_index = min(len(self.timestamps) - 1, self.current_frame_index + 1)
        if new_index != self.current_frame_index:
            self._update_plots_for_frame(new_index)
            print(f"Stepped forward to frame {new_index}")

    @pyqtSlot(int)
    def _slider_value_changed(self, value):
        """Handles the timeline slider being moved."""
        if self.timestamps is None or not (0 <= value < len(self.timestamps)):
            return
        # Only update if the index actually changes
        if value != self.current_frame_index:
            self._update_plots_for_frame(value)

    @pyqtSlot()
    def _pause_on_slider_press(self):
        """Pauses playback when the user starts dragging the slider."""
        if self.is_playing:
            self.play_pause_button.setChecked(False) # This triggers _toggle_playback to pause

    def closeEvent(self, event):
        """Stops timer on close."""
        self.playback_timer.stop()
        self.feature_plot_window.close() # Close feature window as well
        self.pca_vector_window.close() # Close PCA window
        event.accept()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Tune Signal Processing using Recorded Data")
    parser.add_argument(
        "npz_file",
        nargs='?', # Makes the argument optional
        help=f"Path to the raw_pipeline_data.npz file. If omitted, tries to find the latest run in '{DEFAULT_RECORDING_DIR}'.",
        default=None
    )
    args = parser.parse_args()

    npz_path = args.npz_file
    if npz_path is None:
        print("No NPZ file provided, searching for latest run...")
        try:
            runs = [d for d in os.listdir(DEFAULT_RECORDING_DIR) if os.path.isdir(os.path.join(DEFAULT_RECORDING_DIR, d)) and d.startswith('run_')]
            if not runs:
                raise FileNotFoundError(f"No run directories found in {DEFAULT_RECORDING_DIR}")
            latest_run = sorted(runs)[-1]
            print(f"Found latest run: {latest_run}")
            npz_path = os.path.join(DEFAULT_RECORDING_DIR, latest_run, DEFAULT_NPZ_FILE)
        except FileNotFoundError as e:
            print(f"Error: {e}")
            sys.exit(1)
        except Exception as e:
            print(f"Error searching for latest run: {e}")
            sys.exit(1)

    if not os.path.exists(npz_path):
        print(f"Error: Specified or found NPZ file does not exist: {npz_path}")
        sys.exit(1)

    app = QApplication(sys.argv)
    window = TuningWindow(npz_file_path=npz_path)
    window.show()
    sys.exit(app.exec())