#!/usr/bin/env python3

"""
Script for tuning SignalGenerator and SignalProcessor parameters using recorded data.

Loads raw signal and feature coordinate data from an .npz file generated by
the main application's recorder. Allows interactive adjustment of processing
parameters and visualizes the raw and filtered signals.
"""

import sys
import os
import time
import numpy as np
import traceback
import argparse
import json

# --- PyQt6 Imports ---
try:
    from PyQt6.QtWidgets import (
        QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
        QGroupBox, QFormLayout, QLabel, QDoubleSpinBox, QComboBox,
        QPushButton, QSizePolicy, QSpacerItem, QFileDialog, QCheckBox, QMessageBox, QGridLayout
    )
    from PyQt6.QtCore import QTimer, Qt, pyqtSlot
    from PyQt6.QtGui import QFont
    import pyqtgraph as pg
    print("Using PyQt6 and pyqtgraph")
except ImportError as e:
    print(f"Fatal Error: Missing required libraries (PyQt6, pyqtgraph). {e}")
    print("Please install them (e.g., pip install PyQt6 pyqtgraph)")
    sys.exit(1)

# --- Add src directory to Python path ---
script_dir = os.path.dirname(os.path.abspath(__file__))
src_dir = os.path.join(script_dir, '..', 'src')
if src_dir not in sys.path:
    sys.path.insert(0, src_dir)
    print(f"Added '{src_dir}' to Python path.")

# --- Import Processing Components ---
try:
    from signal_generator import SignalGenerator
    from signal_processor import SignalProcessor
except ImportError as e:
    print(f"Fatal Error: Failed to import SignalGenerator or SignalProcessor from 'src': {e}")
    traceback.print_exc()
    sys.exit(1)

# --- Constants ---
DEFAULT_RECORDING_DIR = os.path.abspath(os.path.join(script_dir, '..', 'recordings'))
DEFAULT_RUN_NAME = "run_1" # Placeholder, adjust as needed or use argparse
DEFAULT_NPZ_FILE = "raw_pipeline_data.npz"

# --- Feature Plot Window ---
class FeaturePlotWindow(QWidget):
    """A separate window to display feature points (X vs Y) for a specific time."""
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Feature Point Positions")
        # Initial size will be set relative to the main window later

        self.timestamps = None
        self.feature_coords = None # List of arrays
        self.center_of_mass = np.array([0.0, 0.0]) # Store the initial center
        self.initial_plot_set = False # Flag to set range only once

        layout = QVBoxLayout(self)
        self.plot_widget = pg.PlotWidget()
        layout.addWidget(self.plot_widget)

        self.plot_widget.setAspectLocked(True) # Ensure X and Y scales are equal
        self.plot_widget.setLabel('left', 'Y Coordinate')
        self.plot_widget.setLabel('bottom', 'X Coordinate')
        self.plot_widget.showGrid(x=True, y=True, alpha=0.3)
        # Invert Y axis to match typical image coordinates (optional)
        self.plot_widget.invertY(True)

        self.scatter_item = pg.ScatterPlotItem(size=5, pen=None, brush='r')
        self.plot_widget.addItem(self.scatter_item)

        # Set larger font for axes if needed (can inherit from main window later)
        # default_font = QApplication.font()
        # self.plot_widget.getAxis('left').setTickFont(default_font)
        # self.plot_widget.getAxis('bottom').setTickFont(default_font)

    def set_data(self, timestamps, feature_coords):
        self.timestamps = timestamps
        self.feature_coords = feature_coords
        print(f"[FeatureWindow] Received data: {len(timestamps)} timestamps, {len(feature_coords)} coord sets.")

        # --- Calculate initial center of mass ---
        self.center_of_mass = np.array([0.0, 0.0]) # Reset
        # --- MODIFIED: Explicitly check for None before checking length ---
        if self.feature_coords is not None and len(self.feature_coords) > 0: # Check if feature_coords exists and is not empty
            first_frame_points = self.feature_coords[0]
            if first_frame_points is not None and first_frame_points.ndim >= 2 and first_frame_points.shape[-1] == 2 and len(first_frame_points) > 0:
                # Reshape to (N, 2) and calculate mean
                points_2d = first_frame_points.reshape(-1, 2)
                self.center_of_mass = np.mean(points_2d, axis=0)
                # --- Calculate initial relative points for range setting ---
                initial_relative_points = points_2d - self.center_of_mass
                print(f"[FeatureWindow] Calculated initial center of mass: {self.center_of_mass}") # Keep this print
                # --- ADDED DEBUG PRINT ---
                print(f"[FeatureWindow Debug] Center X: {self.center_of_mass[0]:.2f}, Center Y: {self.center_of_mass[1]:.2f}")

                # --- Calculate overall range based on ALL relative points ---
                all_relative_points_list = []
                for frame_points in self.feature_coords:
                    if frame_points is not None and frame_points.ndim >= 2 and frame_points.shape[-1] == 2 and len(frame_points) > 0:
                        relative = frame_points.reshape(-1, 2) - self.center_of_mass
                        all_relative_points_list.append(relative)

                if all_relative_points_list:
                    all_relative_points = np.vstack(all_relative_points_list)
                    min_x, max_x = np.min(all_relative_points[:, 0]), np.max(all_relative_points[:, 0])
                    min_y, max_y = np.min(all_relative_points[:, 1]), np.max(all_relative_points[:, 1])
                    padding_factor = 1.1 # Add 10% padding
                    # Calculate range width/height and center it
                    range_x = (max_x - min_x) * padding_factor
                    range_y = (max_y - min_y) * padding_factor
                    center_x = (max_x + min_x) / 2
                    center_y = (max_y + min_y) / 2
                    self.initial_plot_range = ((center_x - range_x / 2, center_x + range_x / 2),
                                               (center_y - range_y / 2, center_y + range_y / 2))
                    print(f"[FeatureWindow] Calculated overall plot range: X={self.initial_plot_range[0]}, Y={self.initial_plot_range[1]}")
                else:
                    self.initial_plot_range = None # Fallback if no valid points found after first frame
            else:
                print("[FeatureWindow] Warning: No valid points in the first frame to calculate center of mass.")
                points_2d = None # Ensure points_2d is defined
                self.initial_plot_range = None
        else:
            print("[FeatureWindow] Warning: No feature coordinate data provided.")
            points_2d = None # Ensure points_2d is defined

    def update_plot(self, frame_index):
        if self.feature_coords is None or not (0 <= frame_index < len(self.feature_coords)):
            self.scatter_item.setData([]) # Clear plot if index is invalid
            self.plot_widget.setTitle("Feature Points (No Data)")
            return

        points = self.feature_coords[frame_index]
        # --- MODIFIED: Check for (N, 2) or (N, 1, 2) shape ---
        if points is not None and points.ndim >= 2 and points.shape[-1] == 2:
            # Reshape to (N, 2) if necessary
            points_to_plot = points.reshape(-1, 2)
            # Subtract center of mass
            relative_points = points_to_plot - self.center_of_mass
            # --- Plot relative points ---
            self.scatter_item.setData(pos=relative_points)

            # --- Set range and disable auto-range ONCE after first plot ---
            if not self.initial_plot_set:
                if self.initial_plot_range: # Use calculated overall range if available
                    self.plot_widget.setXRange(*self.initial_plot_range[0], padding=0)
                    self.plot_widget.setYRange(*self.initial_plot_range[1], padding=0)
                    self.plot_widget.getViewBox().disableAutoRange()
                    self.initial_plot_set = True
                print(f"[FeatureWindow] Set fixed plot range and disabled auto-range.")

            current_time = self.timestamps[frame_index] if self.timestamps is not None else 0.0
            self.plot_widget.setTitle(f"Relative Feature Points @ {current_time:.2f}s (Frame {frame_index})")
        else:
            self.scatter_item.setData([]) # Clear plot if data for frame is invalid
            # --- DEBUG PRINT ---
            print(f"[FeatureWindow Debug] Invalid data at index {frame_index}. Type: {type(points)}, Shape: {points.shape if hasattr(points, 'shape') else 'N/A'}, Is None: {points is None}")
            self.plot_widget.setTitle(f"Feature Points (Invalid Data @ Frame {frame_index})")

class TuningWindow(QMainWindow):
    """Main window for the signal processing tuning application."""

    def __init__(self, npz_file_path, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Signal Processing Tuner")
        # --- Make main window wider ---
        self.setGeometry(100, 100, 1200, 800) # Increased width from 1000 to 1200

        # Data storage
        self.timestamps = None
        self.raw_signal_loaded = None
        self.feature_coords = None
        self.sampling_rate = 30.0 # Default, will be updated from data

        # Processed data storage
        self.raw_signal_processed = None
        self.filtered_signal_processed = None

        # Processing components
        self.signal_generator = None
        self.signal_processor = None

        # Playback state
        self.playback_timer = QTimer(self)
        self.playback_timer.timeout.connect(self._update_playback_cursor)
        self.current_frame_index = 0
        self.playback_start_time = 0
        self.is_playing = False
        self.playback_speed = 1.0 # Added playback speed multiplier

        # --- Set Larger Font ---
        default_font = QApplication.font()
        default_point_size = default_font.pointSize()
        if default_point_size < 8: default_point_size = 10 # Ensure a minimum base size
        new_point_size = int(default_point_size * 1.08) # Increase by 8%
        self.larger_font = QFont(default_font)
        self.larger_font.setPointSize(new_point_size)
        self.setFont(self.larger_font)
        print(f"[UI] Setting base font size to {new_point_size}pt (was {default_point_size}pt)")

        # --- Create Feature Plot Window ---
        self.feature_plot_window = FeaturePlotWindow()
        self.feature_plot_window.setFont(self.larger_font) # Apply larger font
        # --- Position feature window next to main window ---
        main_geo = self.geometry()
        feature_win_x = main_geo.x() + main_geo.width() + 10 # Position to the right with a small gap
        feature_win_y = main_geo.y()
        feature_win_height = main_geo.height() # Match main window height
        feature_win_width = feature_win_height # Make width equal to height (square)
        self.feature_plot_window.setGeometry(feature_win_x, feature_win_y, feature_win_width, feature_win_height)

        self._init_ui()
        self.load_data(npz_file_path)
        self._reprocess_data() # Initial processing and plot population
        # --- Show feature plot window by default ---
        self.feature_plot_window.show()

    def _init_ui(self):
        """Creates and arranges UI elements."""
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        main_layout = QHBoxLayout(central_widget) # Horizontal: Plots | Controls

        # --- Plots Area ---
        plot_widget_container = QWidget()
        plot_layout = QVBoxLayout(plot_widget_container)

        # --- Plot Appearance Changes ---
        pg.setConfigOption('background', 'k') # Black background
        pg.setConfigOption('foreground', 'w') # White foreground (axes, labels)

        self.raw_plot_widget = pg.PlotWidget(title="Raw Motion Signal")
        self.raw_plot_widget.setLabel('left', 'Amplitude')
        self.raw_plot_widget.showGrid(x=True, y=True, alpha=0.3)
        # Make line thicker (width=2) and brighter blue
        self.raw_plot_widget.getAxis('left').setTickFont(self.larger_font) # Apply font to axis ticks
        self.raw_plot_curve = self.raw_plot_widget.plot(pen=pg.mkPen(color=(100, 100, 255), width=2))
        self.raw_time_cursor = pg.InfiniteLine(angle=90, movable=False, pen='r')
        self.raw_plot_widget.addItem(self.raw_time_cursor)

        self.filtered_plot_widget = pg.PlotWidget(title="Filtered Signal")
        self.filtered_plot_widget.setLabel('left', 'Amplitude')
        self.filtered_plot_widget.getAxis('left').setTickFont(self.larger_font) # Apply font to axis ticks
        self.filtered_plot_widget.setLabel('bottom', 'Time (s)', color='white') # Ensure label color matches foreground
        self.filtered_plot_widget.showGrid(x=True, y=True, alpha=0.3)
        self.filtered_plot_curve = self.filtered_plot_widget.plot(pen='g')
        self.filtered_time_cursor = pg.InfiniteLine(angle=90, movable=False, pen='r')
        self.filtered_plot_widget.addItem(self.filtered_time_cursor)

        # Link X axes
        self.filtered_plot_widget.setXLink(self.raw_plot_widget)
        # Apply font to bottom axis ticks (only need to set on one linked axis)
        self.filtered_plot_widget.getAxis('bottom').setTickFont(self.larger_font)
        # --- End Plot Appearance Changes ---


        plot_layout.addWidget(self.raw_plot_widget)
        plot_layout.addWidget(self.filtered_plot_widget)

        main_layout.addWidget(plot_widget_container, 3) # Give plots more space

        # --- Controls Area ---
        controls_container = QWidget()
        controls_container.setSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Preferred)
        controls_layout = QVBoxLayout(controls_container)

        # Playback Controls
        playback_group = QGroupBox("Playback")
        playback_layout = QGridLayout(playback_group) # Use grid for better alignment
        self.play_pause_button = QPushButton("Play")
        self.play_pause_button.setCheckable(True)
        self.play_pause_button.toggled.connect(self._toggle_playback)
        self.reset_button = QPushButton("Reset")
        self.reset_button.clicked.connect(self._reset_playback)

        # --- Playback Speed Control ---
        speed_label = QLabel("Speed:")
        speed_label.setFont(self.larger_font)
        self.speed_combo = QComboBox()
        self.speed_combo.addItems(["1x", "0.5x", "0.25x", "0.125x"])
        self.speed_combo.setFont(self.larger_font)
        self.speed_combo.currentIndexChanged.connect(self._update_playback_speed)
        # --- End Playback Speed Control ---

        playback_layout.addWidget(self.play_pause_button, 0, 0)
        playback_layout.addWidget(self.reset_button, 0, 1)
        playback_layout.addWidget(speed_label, 1, 0, Qt.AlignmentFlag.AlignRight)
        playback_layout.addWidget(self.speed_combo, 1, 1)
        controls_layout.addWidget(playback_group)
        # Apply font to group box title
        playback_group.setFont(self.larger_font)

        # --- Profile Management ---
        profile_group = QGroupBox("Profile Management")
        profile_layout = QVBoxLayout(profile_group)
        self.load_profile_button = QPushButton("Load Profile...")
        self.save_profile_button = QPushButton("Save Profile As...")
        self.load_profile_button.clicked.connect(self._load_profile)
        self.save_profile_button.clicked.connect(self._save_profile_as)
        profile_h_layout = QHBoxLayout()
        profile_h_layout.addWidget(self.load_profile_button)
        profile_h_layout.addWidget(self.save_profile_button)
        profile_layout.addLayout(profile_h_layout)
        controls_layout.addWidget(profile_group)

        # --- Show Features Button ---
        self.show_features_button = QPushButton("Show Feature Plot")
        self.show_features_button.clicked.connect(self.feature_plot_window.show)
        controls_layout.addWidget(self.show_features_button)
        # --- End Show Features Button ---

        # Apply font to group box title
        profile_group.setFont(self.larger_font)
        # --- End Profile Management ---

        # Signal Generator Settings (Optional - if recalculating raw signal)
        sg_group = QGroupBox("Signal Generation")
        sg_layout = QFormLayout(sg_group)
        self.aggMethod_combo = QComboBox()
        self.aggMethod_combo.addItems(["median", "mean"])
        self.aggMethod_combo.setFont(self.larger_font) # Apply font
        self.recalc_raw_checkbox = QCheckBox("Recalculate Raw Signal")
        self.recalc_raw_checkbox.setToolTip("Recalculate raw signal from feature points using selected method.")
        self.recalc_raw_checkbox.setFont(self.larger_font) # Apply font
        sg_layout.addRow(self.recalc_raw_checkbox)
        sg_agg_label = QLabel("Aggregation:") # Create label explicitly
        sg_agg_label.setFont(self.larger_font) # Apply font
        sg_layout.addRow(sg_agg_label, self.aggMethod_combo)
        controls_layout.addWidget(sg_group)
        # Apply font to group box title
        sg_group.setFont(self.larger_font)

        # Signal Processor Settings
        sp_group = QGroupBox("Signal Processing")
        sp_layout = QFormLayout(sp_group)
        self.filtLow_spin = QDoubleSpinBox(minimum=0.05, maximum=1.00, singleStep=0.01, decimals=2, value=0.1)
        self.filtHigh_spin = QDoubleSpinBox(minimum=0.10, maximum=5.00, singleStep=0.05, decimals=2, value=1.0)
        self.filtLow_spin.setFont(self.larger_font) # Apply font
        self.filtHigh_spin.setFont(self.larger_font) # Apply font
        self.filtType_combo = QComboBox()
        self.filtType_combo.addItems(["lfilter", "filtfilt"])
        self.filtType_combo.setFont(self.larger_font) # Apply font
        self.peakProm_spin = QDoubleSpinBox(minimum=0.0, maximum=10.0, singleStep=0.005, value=0.0, decimals=3)
        self.peakProm_spin.setFont(self.larger_font) # Apply font

        self.filtLow_spin.setToolTip("Lower cutoff frequency (Hz) for bandpass filter.")
        self.filtHigh_spin.setToolTip("Upper cutoff frequency (Hz) for bandpass filter.")
        self.filtType_combo.setToolTip("Filter method: lfilter (causal) or filtfilt (zero-phase).")
        self.peakProm_spin.setToolTip("Minimum peak prominence for peak detection (0 = disabled).")

        sp_layout.addRow("Filter Low (Hz):", self.filtLow_spin)
        sp_layout.addRow("Filter High (Hz):", self.filtHigh_spin)
        sp_layout.addRow("Filter Method:", self.filtType_combo)
        sp_peak_label = QLabel("Peak Prominence:") # Create label explicitly
        sp_peak_label.setFont(self.larger_font) # Apply font
        sp_layout.addRow(sp_peak_label, self.peakProm_spin)
        controls_layout.addWidget(sp_group)
        # Apply font to group box title
        sp_group.setFont(self.larger_font)
        # Apply font to form layout labels (requires iterating or explicit creation)
        # Explicit creation is safer if layout changes
        sp_layout.labelForField(self.filtLow_spin).setFont(self.larger_font)
        sp_layout.labelForField(self.filtHigh_spin).setFont(self.larger_font)
        sp_layout.labelForField(self.filtType_combo).setFont(self.larger_font)

        # Apply Button
        self.apply_button = QPushButton("Apply Settings & Reprocess")
        self.apply_button.clicked.connect(self._reprocess_data)
        controls_layout.addWidget(self.apply_button)

        controls_layout.addStretch(1) # Push controls to the top
        main_layout.addWidget(controls_container, 1) # Give controls less space

        # Connect signals for automatic reprocessing (optional, can rely on button)
        # self.aggMethod_combo.currentIndexChanged.connect(self._reprocess_data)
        # self.recalc_raw_checkbox.stateChanged.connect(self._reprocess_data)
        # self.filtLow_spin.valueChanged.connect(self._reprocess_data)
        # self.filtHigh_spin.valueChanged.connect(self._reprocess_data)
        # self.filtType_combo.currentIndexChanged.connect(self._reprocess_data)
        # self.peakProm_spin.valueChanged.connect(self._reprocess_data)

    def load_data(self, file_path):
        """Loads data from the specified .npz file."""
        print(f"Loading data from: {file_path}")
        try:
            with np.load(file_path, allow_pickle=True) as data:
                if 'timestamps' not in data or 'raw_signal' not in data or 'feature_coords' not in data:
                    raise KeyError("NPZ file missing one or more required keys: 'timestamps', 'raw_signal', 'feature_coords'")

                self.timestamps = data['timestamps']
                self.raw_signal_loaded = data['raw_signal']
                self.feature_coords = data['feature_coords'] # List/array of (N, 2) arrays

                if len(self.timestamps) < 2:
                    print("Warning: Not enough timestamps to calculate sampling rate. Using default.")
                    self.sampling_rate = 30.0
                else:
                    # Calculate average sampling rate from timestamps
                    intervals = np.diff(self.timestamps)
                    mean_interval = np.mean(intervals)
                    if mean_interval > 1e-6:
                        self.sampling_rate = 1.0 / mean_interval
                    else:
                        print("Warning: Mean time interval is near zero. Using default sampling rate.")
                        self.sampling_rate = 30.0

                print(f"Data loaded successfully. Frames: {len(self.timestamps)}, Sampling Rate: {self.sampling_rate:.2f} Hz")
                self.raw_signal_processed = self.raw_signal_loaded.copy() # Start with loaded raw signal
                # --- Pass data to feature window ---
                self.feature_plot_window.set_data(self.timestamps, self.feature_coords)

        except FileNotFoundError:
            print(f"Error: Recording file not found at {file_path}")
            QApplication.quit()
        except Exception as e:
            print(f"Error loading or processing NPZ file: {e}")
            traceback.print_exc()
            QApplication.quit()

    def _apply_settings(self):
        """Reads UI controls and re-initializes processing components."""
        print("Applying settings...")
        sg_config = {'SIGNAL_AGGREGATION_METHOD': self.aggMethod_combo.currentText()}
        sp_config = {
            'SIGNAL_FILTER_LOW_HZ': self.filtLow_spin.value(),
            'SIGNAL_FILTER_HIGH_HZ': self.filtHigh_spin.value(),
            'SIGNAL_FILTER_METHOD': self.filtType_combo.currentText(),
            'PEAK_DETECT_PROMINENCE': self.peakProm_spin.value() if self.peakProm_spin.value() > 1e-6 else None
        }

        try:
            self.signal_generator = SignalGenerator(config=sg_config)
            self.signal_processor = SignalProcessor(config=sp_config, sampling_rate=self.sampling_rate)
            print("SignalGenerator and SignalProcessor re-initialized.")
        except Exception as e:
            print(f"Error re-initializing components: {e}")
            traceback.print_exc()

    def _gather_settings_from_ui(self):
        """Gathers current settings from UI widgets into a dictionary."""
        settings = {
            'feature_tracker': { # Include dummy FT section for structure consistency
                'OPTICAL_FLOW_PARAMS': {} # Add if needed later
            },
            'signal_generator': {
                'SIGNAL_AGGREGATION_METHOD': self.aggMethod_combo.currentText()
            },
            'signal_processor': {
                'SIGNAL_FILTER_LOW_HZ': self.filtLow_spin.value(),
                'SIGNAL_FILTER_HIGH_HZ': self.filtHigh_spin.value(),
                'SIGNAL_FILTER_METHOD': self.filtType_combo.currentText(),
                'PEAK_DETECT_PROMINENCE': self.peakProm_spin.value() if self.peakProm_spin.value() > 1e-6 else None
            }
        }
        return settings

    def _populate_ui_from_settings(self, settings_dict):
        """Populates UI widgets from a settings dictionary."""
        print("[UI] Populating settings widgets from loaded profile.")
        try:
            # Get sections, providing empty dicts as fallback
            sg_settings = settings_dict.get('signal_generator', {})
            sp_settings = settings_dict.get('signal_processor', {})

            # Populate Signal Generator widgets
            agg_method = sg_settings.get('SIGNAL_AGGREGATION_METHOD', 'median')
            self.aggMethod_combo.setCurrentText(agg_method)

            # Populate Signal Processor widgets
            self.filtLow_spin.setValue(sp_settings.get('SIGNAL_FILTER_LOW_HZ', 0.1))
            self.filtHigh_spin.setValue(sp_settings.get('SIGNAL_FILTER_HIGH_HZ', 1.0))
            filt_method = sp_settings.get('SIGNAL_FILTER_METHOD', 'lfilter')
            self.filtType_combo.setCurrentText(filt_method)
            prominence = sp_settings.get('PEAK_DETECT_PROMINENCE')
            self.peakProm_spin.setValue(prominence if prominence is not None else 0.0)

            print("[UI] Settings widgets populated.")

        except Exception as e:
            print(f"Error populating settings widgets: {e}")
            traceback.print_exc()
            QMessageBox.warning(self, "Settings Error", f"Could not fully populate settings widgets from profile:\n{e}")

    @pyqtSlot()
    def _load_profile(self):
        """Opens dialog to load settings from a JSON profile."""
        filePath, _ = QFileDialog.getOpenFileName(
            self, "Load Profile", DEFAULT_RECORDING_DIR, "JSON Files (*.json)"
        )
        if filePath:
            try:
                with open(filePath, 'r') as f:
                    loaded_settings = json.load(f)
                self._populate_ui_from_settings(loaded_settings)
                self._reprocess_data() # Reprocess with newly loaded settings
                print(f"Profile loaded successfully from: {filePath}")
            except Exception as e:
                print(f"Error loading profile: {e}")
                QMessageBox.critical(self, "Load Error", f"Failed to load profile:\n{filePath}\n\n{e}")

    @pyqtSlot()
    def _reprocess_data(self):
        """Applies current settings and reprocesses the entire dataset."""
        if self.timestamps is None:
            print("No data loaded to reprocess.")
            return

        print("Reprocessing all data...")
        self._apply_settings() # Re-init components with current settings

        if self.signal_generator is None or self.signal_processor is None:
            print("Processing components not initialized.")
            return

        # --- Recalculate Raw Signal (Optional) ---
        if self.recalc_raw_checkbox.isChecked():
            print("Recalculating raw signal from feature coordinates...")
            if self.feature_coords is None or len(self.feature_coords) != len(self.timestamps):
                print("Error: Feature coordinate data is missing or length mismatch.")
                return

            recalculated_raw = []
            # Need pairs of frames for displacement
            for i in range(len(self.feature_coords) - 1):
                # Simulate FeatureTracker output: (old_points, new_points)
                # We only have new points for each frame, so use frame i and i+1
                # This assumes feature_coords[i] corresponds to points *at* timestamps[i]
                # A better recording format might store old/new pairs directly.
                # For now, approximate displacement between consecutive frames.
                # Note: This approximation might differ from the original live calculation.
                old_p = self.feature_coords[i]
                new_p = self.feature_coords[i+1]

                # Basic matching by index (crude approximation)
                min_len = min(len(old_p) if old_p is not None else 0, len(new_p) if new_p is not None else 0)
                if min_len > 0:
                    mock_tracked_data = [(old_p[:min_len], new_p[:min_len])]
                    signal_list = self.signal_generator.process_tracked_features(mock_tracked_data)
                    recalculated_raw.append(signal_list[0] if signal_list else 0.0)
                else:
                    recalculated_raw.append(0.0)
            # Pad the last frame signal (no displacement available)
            recalculated_raw.append(recalculated_raw[-1] if recalculated_raw else 0.0)
            self.raw_signal_processed = np.array(recalculated_raw)
            print(f"Raw signal recalculated ({len(self.raw_signal_processed)} points).")
        else:
            # Use the originally loaded raw signal
            self.raw_signal_processed = self.raw_signal_loaded.copy()
            print("Using loaded raw signal.")

        # --- Process Raw Signal ---
        print("Processing raw signal with SignalProcessor...")
        # Resetting is not needed as SignalProcessor is re-initialized in _apply_settings()
        # self.signal_processor.reset()
        # Process the entire raw signal history
        # --- MODIFIED: Process signal value by value ---
        processed_filtered_signal = []
        for raw_value in self.raw_signal_processed:
            self.signal_processor.process_signal_values([raw_value]) # Pass as a list containing one value
            processed_filtered_signal.append(self.signal_processor.get_latest_filtered_value())
        self.filtered_signal_processed = np.array(processed_filtered_signal)
        print(f"Signal processed ({len(self.filtered_signal_processed)} filtered points).")

        # --- Update Plots ---
        valid_timestamps = self.timestamps[:len(self.raw_signal_processed)] # Match length
        self.raw_plot_curve.setData(valid_timestamps, self.raw_signal_processed)
        self.filtered_plot_curve.setData(valid_timestamps, self.filtered_signal_processed)
        print("Plots updated.")
        self._reset_playback() # Reset cursor position after reprocessing

    @pyqtSlot(bool)
    def _toggle_playback(self, checked):
        """Starts or stops the playback timer."""
        if checked:
            if self.timestamps is not None and len(self.timestamps) > 0:
                self.is_playing = True
                self.play_pause_button.setText("Pause")
                self.playback_start_time = time.time() - (self.timestamps[self.current_frame_index] - self.timestamps[0])
                self.playback_timer.start(30) # Update cursor roughly 30 times/sec
                print("Playback started.")
        else:
            self.is_playing = False
            self.play_pause_button.setText("Play")
            self.playback_timer.stop()
            print("Playback paused.")

    @pyqtSlot(int)
    def _update_playback_speed(self, index):
        """Updates the playback speed multiplier based on combo box selection."""
        speed_text = self.speed_combo.itemText(index) # e.g., "0.5x"
        try:
            self.playback_speed = float(speed_text.replace('x', ''))
            print(f"Playback speed set to: {self.playback_speed}x")
        except ValueError:
            self.playback_speed = 1.0 # Default to 1x on error

    @pyqtSlot()
    def _reset_playback(self):
        """Resets the playback cursor to the beginning."""
        self.current_frame_index = 0
        if self.timestamps is not None and len(self.timestamps) > 0:
            current_time = self.timestamps[0]
            self.raw_time_cursor.setPos(current_time)
            self.filtered_time_cursor.setPos(current_time)
            self.feature_plot_window.update_plot(self.current_frame_index) # Update feature plot
        if self.is_playing:
            self.playback_start_time = time.time() # Reset timer baseline
        print("Playback reset.")

    def _update_playback_cursor(self):
        """Updates the position of the time cursor based on simulated time."""
        if not self.is_playing or self.timestamps is None or len(self.timestamps) < 2:
            return

        # --- Incorporate playback speed ---
        elapsed_real_time = time.time() - self.playback_start_time
        elapsed_simulated_time = elapsed_real_time * self.playback_speed
        target_timestamp = self.timestamps[0] + elapsed_simulated_time

        # Find the closest frame index
        # Use searchsorted for efficiency
        self.current_frame_index = np.searchsorted(self.timestamps, target_timestamp, side='right') - 1
        self.current_frame_index = max(0, self.current_frame_index) # Ensure non-negative

        # Loop playback
        if self.current_frame_index >= len(self.timestamps) - 1:
            self.current_frame_index = 0
            # Reset timer baseline accounting for speed
            self.playback_start_time = time.time()
            current_time = self.timestamps[0]
        else:
            current_time = self.timestamps[self.current_frame_index]

        # Update cursor positions
        self.raw_time_cursor.setPos(current_time)
        self.filtered_time_cursor.setPos(current_time)

        # --- Update feature plot window ---
        self.feature_plot_window.update_plot(self.current_frame_index)

    @pyqtSlot()
    def _save_profile_as(self):
        """Opens dialog to save current UI settings to a JSON profile."""
        filePath, _ = QFileDialog.getSaveFileName(
            self, "Save Profile As...", DEFAULT_RECORDING_DIR, "JSON Files (*.json)"
        )
        if filePath:
            if not filePath.lower().endswith('.json'):
                filePath += '.json'

            current_settings = self._gather_settings_from_ui()
            try:
                with open(filePath, 'w') as f:
                    json.dump(current_settings, f, indent=4)
                print(f"Profile saved successfully to: {filePath}")
                QMessageBox.information(self, "Save Successful", f"Settings saved to:\n{filePath}")
            except Exception as e:
                print(f"Error saving profile: {e}")
                QMessageBox.critical(self, "Save Error", f"Failed to save profile:\n{filePath}\n\n{e}")

    def closeEvent(self, event):
        """Stops timer on close."""
        self.playback_timer.stop()
        self.feature_plot_window.close() # Close feature window as well
        event.accept()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Tune Signal Processing using Recorded Data")
    parser.add_argument(
        "npz_file",
        nargs='?', # Makes the argument optional
        help=f"Path to the raw_pipeline_data.npz file. If omitted, tries to find the latest run in '{DEFAULT_RECORDING_DIR}'.",
        default=None
    )
    args = parser.parse_args()

    npz_path = args.npz_file
    if npz_path is None:
        print("No NPZ file provided, searching for latest run...")
        try:
            runs = [d for d in os.listdir(DEFAULT_RECORDING_DIR) if os.path.isdir(os.path.join(DEFAULT_RECORDING_DIR, d)) and d.startswith('run_')]
            if not runs:
                raise FileNotFoundError(f"No run directories found in {DEFAULT_RECORDING_DIR}")
            latest_run = sorted(runs)[-1]
            print(f"Found latest run: {latest_run}")
            npz_path = os.path.join(DEFAULT_RECORDING_DIR, latest_run, DEFAULT_NPZ_FILE)
        except FileNotFoundError as e:
            print(f"Error: {e}")
            sys.exit(1)
        except Exception as e:
            print(f"Error searching for latest run: {e}")
            sys.exit(1)

    if not os.path.exists(npz_path):
        print(f"Error: Specified or found NPZ file does not exist: {npz_path}")
        sys.exit(1)

    app = QApplication(sys.argv)
    window = TuningWindow(npz_file_path=npz_path)
    window.show()
    sys.exit(app.exec())